bl-beepmein-pipemenu: add --standalone option for launchers, update help

diff --git a/bin/bl-beepmein-pipemenu b/bin/bl-beepmein-pipemenu
--- a/bin/bl-beepmein-pipemenu
+++ b/bin/bl-beepmein-pipemenu
@@ -22,15 +22,24 @@ Usage: bl-beepmein-pipemenu | jgmenu --simple --icon-size=0
     It can be called from a tint2 button, launcher or jgmenu menu.
 
 Options:
-    -h --help   show this message
+    -h --help
+        show this message
 
-    If bl-beepmein-pipemenu is called with no options (the usual method),
+    -s --standalone
+        call jgmenu directly
+
+    If bl-beepmein-pipemenu is called with no options,
     it will output a jgmenu pipemenu for using the beepmein alarm clock.
+
+    The standalone option can be used to start the menu from a launcher
+    like a tint2 button instead of incorporating it in a menu.
 
 Example:
     To launch from the tint2 clock right-click action:
-clock_rclick_command = bash -c \"beepmein-pipemenu | jgmenu --simple --icon-size=0 --config-file=<( sed '/menu_padding_top/ s/^/#/' ~/.config/jgmenu/jgmenurc )\"
+clock_rclick_command = beepmein-pipemenu --standalone
 
+See also:
+    beepmein(1)
 "
 # look for a help option somewhere
 for i in "$@"
@@ -39,6 +48,11 @@ do
     -h|--help)
         echo "$HELP"
         exit 0
+        ;;
+    -s|--standalone)
+        exec jgmenu --csv-cmd="$0" --simple --icon-size=0 --config-file=<( sed '/menu_padding_top/ s/^/#/' ~/.config/jgmenu/jgmenurc )
+        echo "${0}: failed to launch jgmenu" >&2
+        exit 1
         ;;
     esac
 done
