Add GPL3 headers, enhance graphics and remote-desktop pipemenus
Add GPL3 headers to all scripts.
bl-graphics-pipemenu: Add option to install Gimp extras.
bl-remote-desktop-pipemenu: Install dconf-editor, edit server "preferences" menu item.
bl-sshconfig-pipemenu: Correct x-terminal-editor command syntax.
bl-dropbox-pipemenu: Use yad functions from yad-includes in bunsen-common.
bl-help-pipemenu: Restore missing "Bunsen Help Files" submenu.
debian/control: Remove dependency on scrot.
Improve error reporting slightly.

diff --git a/bin/bl-compositor b/bin/bl-compositor
--- a/bin/bl-compositor
+++ b/bin/bl-compositor
@@ -1,18 +1,32 @@
 #!/bin/bash
-# bl-compositor
-# Openbox Pipe Menu for use with compton compositor
-# Originally written for CrunchBang Linux <http://crunchbang.org/>
-# by Philip Newborough <corenominal@corenominal.org>
-# Adapted for Bunsen Labs Linux.
+#    bl-compositor an Openbox Pipe Menu for use with compton compositor
+#    Copyright (C) 2012 Philip Newborough   <corenominal@corenominal.org>
+#    Copyright (C) 2013 Aleks-Daniel Jakimenko
+#    Copyright (C) 2015 John Crawley    <john@bunsenlabs.org>
+#
+#    This program is free software: you can redistribute it and/or modify
+#    it under the terms of the GNU General Public License as published by
+#    the Free Software Foundation, either version 3 of the License, or
+#    (at your option) any later version.
+#
+#    This program is distributed in the hope that it will be useful,
+#    but WITHOUT ANY WARRANTY; without even the implied warranty of
+#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
+#    GNU General Public License for more details.
+#
+#    You should have received a copy of the GNU General Public License
+#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 
 RESTART_ATTEMPTS=20 # times to try killall before reverting to -s KILL
 
 BL_COMMON_LIBDIR='/usr/lib/bunsen/bunsen-common'
 
 if ! . "$BL_COMMON_LIBDIR/bl-include.cfg" 2> /dev/null; then
-    echo $"Error: Failed to locate bl-include.cfg in $BL_COMMON_LIBDIR" >&2
+    echo $"Error: Failed to source bl-include.cfg in $BL_COMMON_LIBDIR" >&2
     exit 1
 fi
+
+declareDependencies compton
 
 # ------------- Set compton command options -----------------------------------
 EXECXCOMP='compton'
@@ -23,10 +37,10 @@ fi
 forcekill_compton() {
     killall -q compton
     for (( i=0; i < RESTART_ATTEMPTS; i++ )); do
-        pidof compton > /dev/null || # no process found! Safe to start again
+        pidof compton > /dev/null ||
             break
 
-        (( i == RESTART_ATTEMPTS - 1 )) && # still didn't die? Probably hangs. Force it to die!
+        (( i == RESTART_ATTEMPTS - 1 )) &&
             killall -q -S KILL compton
 
         sleep 0.25
@@ -60,7 +74,7 @@ elif [[ $1 = '--restart' ]]; then
     fi
 elif [[ $1 = '--watch' ]]; then
     while inotifywait -e close_write "$HOME/.config/compton.conf"; do
-        "$0" --restart # TODO move this to function?
+        "$0" --restart
     done
 else
     # Output Openbox menu
diff --git a/bin/bl-conky-pipemenu b/bin/bl-conky-pipemenu
--- a/bin/bl-conky-pipemenu
+++ b/bin/bl-conky-pipemenu
@@ -1,7 +1,19 @@
 #!/bin/bash
+#    bl-conky-pipemenu - an Openbox pipemenu for manipulating conky
+#    Copyright (C) 2015 damo <damo@bunsenlabs.org>
 #
-# bl-conky-pipemenu
-# Written for BunsenLabs Linux by damo <damo@bunsenlabs.org> April 2015
+#    This program is free software: you can redistribute it and/or modify
+#    it under the terms of the GNU General Public License as published by
+#    the Free Software Foundation, either version 3 of the License, or
+#    (at your option) any later version.
+#
+#    This program is distributed in the hope that it will be useful,
+#    but WITHOUT ANY WARRANTY; without even the implied warranty of
+#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
+#    GNU General Public License for more details.
+#
+#    You should have received a copy of the GNU General Public License
+#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 
 BL_COMMON_LIBDIR='/usr/lib/bunsen/bunsen-common'
 
@@ -14,7 +26,7 @@ CSESSION="bl-conky-session"
 HELPFILE="/usr/share/bunsen/bunsen-docs/helpfile-conkyzen.txt"
 
 if ! . "$BL_COMMON_LIBDIR/bl-include.cfg" 2> /dev/null; then
-    echo $"Error: Failed to locate bl-include.cfg in $BL_COMMON_LIBDIR" >&2
+    echo $"Error: Failed to source bl-include.cfg in $BL_COMMON_LIBDIR" >&2
     exit 1
 fi
 if [ ! -e "$CSESSIONFILE" ] 2> /dev/null ; then
@@ -24,6 +36,8 @@ fi
 if [ ! -e "$SESSIONS" ] 2> /dev/null ; then
     echo $"Error: Failed to locate saved-sessions in $CONKYPATH" >&2
 fi
+
+declareDependencies yad bl-conkyzen bl-conky-session
 
 getSessions(){  # read any saved sessions from save-sessions file
     menuItem "Default" "$CSESSION $CSESSIONFILE"
@@ -43,8 +57,8 @@ loadEditmenu(){
             menuItem "$CONKY" "bl-text-editor $CPATH"
         done < "$CSESSIONFILE"
         menuSubmenuEnd
-    else 
-        menuItem "No Running Conkys" 
+    else
+        menuItem "No Running Conkys"
     fi
 }
 
@@ -75,14 +89,14 @@ menuStart "Conkymenu" "Conky"
 menuItem "Conky Chooser" "$CZEN"
 menuItem "Reload Conkys" "$CSESSION"
 getConkys
-menuSeparator 
+menuSeparator
 menuItem "Pin moveable Conkys" "bl-conkypin"
-menuSeparator 
+menuSeparator
 menuItem "New Conky Session" "bl-conkyzen -z"
 menuSubmenu "Sessions" "Saved Sessions"
 getSessions
 menuSubmenuEnd
-menuSeparator 
+menuSeparator
 checkHelpfile
 menuEnd
 
diff --git a/bin/bl-dropbox-pipemenu b/bin/bl-dropbox-pipemenu
--- a/bin/bl-dropbox-pipemenu
+++ b/bin/bl-dropbox-pipemenu
@@ -1,11 +1,21 @@
 #!/bin/bash
-# --------------------------------------------------------------------
-# An Openbox pipemenu for use with Dropbox and Bunsen Labs Linux.
-# Originally written for CrunchBang Linux <http://crunchbanglinux.org/>
-# by Philip Newborough (aka corenominal) <mail@philipnewborough.co.uk>
-# Rewritten by Aleks-Daniel Jakimenko in 2013 and
-# John Crawley <john@bunsenlabs.org> in 2015-2016 to use dropbox.py.
-# --------------------------------------------------------------------
+#    bl-dropbox-pipemenu - an Openbox pipemenu for use with Dropbox
+#    Copyright (C) 2012 Philip Newborough <corenominal@corenominal.org>
+#    Copyright (C) 2013 Aleks-Daniel Jakimenko
+#    Copyright (C) 2015-2016  John Crawley <john@bunsenlabs.org>
+#
+#    This program is free software: you can redistribute it and/or modify
+#    it under the terms of the GNU General Public License as published by
+#    the Free Software Foundation, either version 3 of the License, or
+#    (at your option) any later version.
+#
+#    This program is distributed in the hope that it will be useful,
+#    but WITHOUT ANY WARRANTY; without even the implied warranty of
+#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
+#    GNU General Public License for more details.
+#
+#    You should have received a copy of the GNU General Public License
+#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 
 # Directory to install the dropbox cli interface, dropbox.py.
 # If dropbox.py is in user's $PATH they can use that command
@@ -24,23 +34,17 @@ PROMPT_DELAY_VARIANTS=(FAlSE 0 FALSE 10 FALSE 20 FALSE 30 FALSE 40 FALSE 50 TRUE
 
 BL_COMMON_LIBDIR='/usr/lib/bunsen/bunsen-common'
 
-if ! . "$BL_COMMON_LIBDIR/bl-include.cfg" 2> /dev/null; then
-    echo $"Error: Failed to locate bl-include.cfg in $BL_COMMON_LIBDIR" >&2
-    exit 1
-fi
+for i in bl-include.cfg yad-includes
+do
+    if ! . "$BL_COMMON_LIBDIR/$i" 2> /dev/null; then
+        echo "Error: Failed to source $i in $BL_COMMON_LIBDIR" >&2
+        exit 1
+    fi
+done
 
-yad_common_args=('--window-icon=distributor-logo-bunsenlabs' '--center' '--borders=20')
+declareDependencies wget
+
 yad_common_args+=('--title=Dropbox Installation' '--image=dropbox')
-yad_popup_args=('--undecorated' '--fixed' '--on-top')
-yad_question(){
-    yad --text="$1" --button=Yes:0 --button=No:1 "${yad_common_args[@]}" "${yad_popup_args[@]}"
-    }
-yad_info(){
-    yad --text="$1" --button=OK "${yad_common_args[@]}" "${yad_popup_args[@]}"
-    }
-yad_error(){
-    yad --text="$1" --button=OK "${yad_common_args[@]}" "${yad_popup_args[@]}" --image=dialog-error
-    }
 
 dropbox_is_installed() {
     [[ -x "$USERDBDIR/dropboxd" ]] || return 1
@@ -149,8 +153,6 @@ else
     menuStart
     if ! dropbox_is_installed; then
         menuItem 'Install Dropbox' "$0 --install-dropbox"
-        menuSeparator
-        menuItem 'Find out more about Dropbox' 'x-www-browser http://db.tt/5mJg9lb'
     else
         [[ -d $HOME/Dropbox ]] &&
             menuItem 'Open Dropbox Folder' "bl-file-manager $HOME/Dropbox"
diff --git a/bin/bl-help-pipemenu b/bin/bl-help-pipemenu
--- a/bin/bl-help-pipemenu
+++ b/bin/bl-help-pipemenu
@@ -1,12 +1,24 @@
 #!/bin/bash
+#    bl-help-pipemenu - an Openbox pipemenu for displaying help files
+#    Copyright (C) 2015 damo    <damo@bunsenlabs.org>
 #
-# bl-help-pipemenu
-# Prepared for BunsenLabs Linux by damo <damo@bunsenlabs.org> March 2015
+#    This program is free software: you can redistribute it and/or modify
+#    it under the terms of the GNU General Public License as published by
+#    the Free Software Foundation, either version 3 of the License, or
+#    (at your option) any later version.
+#
+#    This program is distributed in the hope that it will be useful,
+#    but WITHOUT ANY WARRANTY; without even the implied warranty of
+#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
+#    GNU General Public License for more details.
+#
+#    You should have received a copy of the GNU General Public License
+#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 
 BL_COMMON_LIBDIR='/usr/lib/bunsen/bunsen-common'
 
 if ! . "$BL_COMMON_LIBDIR/bl-include.cfg" 2> /dev/null; then
-    echo $"Error: Failed to locate bl-include.cfg in $BL_COMMON_LIBDIR" >&2
+    echo $"Error: Failed to source bl-include.cfg in $BL_COMMON_LIBDIR" >&2
     exit 1
 fi
 
@@ -68,5 +80,11 @@ menuItem 'dmenu' 'x-terminal-emulator -T "dmenu man page" -e man dmenu'
 menuItem 'gmrun' 'x-terminal-emulator -T "gmrun man page" -e man gmrun'
 menuItem 'xrandr' 'x-terminal-emulator -T "xrandr man page" -e man xrandr'
 
+menuSeparator
+menuSubmenu 'BL help' 'Bunsen Help Files'
+menuItem 'How to Edit Menu' 'yad--button="OK":0 --center --window-icon=distributor-logo-bunsenlabs --text-info --title="How to Edit the Menu" --filename="/usr/share/bunsen/bunsen-docs/helpfile-menu.txt" --width=900 --height=700 --fontname=Monospace'
+menuItem 'About Bunsen Alternatives' 'yad --button="OK":0 --center --window-icon=distributor-logo-bunsenlabs --text-info --title="About Bunsen Alternatives" --filename="/usr/share/bunsen/bunsen-docs/helpfile-bl-alternatives.txt" --width=900 --height=700 --fontname=Monospace'
+menuItem 'Conkyzen Help' 'yad --button="OK":0 --center --window-icon=distributor-logo-bunsenlabs --text-info --title="Conkyzen Help" --filename="/usr/share/bunsen/bunsen-docs/helpfile-conkyzen.txt" --width=900 --height=700 --fontname=Monospace'
+menuSubmenuEnd
 
 menuEnd
diff --git a/bin/bl-multimedia-pipemenu b/bin/bl-multimedia-pipemenu
--- a/bin/bl-multimedia-pipemenu
+++ b/bin/bl-multimedia-pipemenu
@@ -1,28 +1,33 @@
 #!/bin/bash
-# ---------------------------------------------------------------------
-# An Openbox pipemenu for Multimedia applications.
+#    bl-multimedia-pipemenu - an Openbox pipemenu for Multimedia applications
+#    Copyright (C) 2012 Philip Newborough   <corenominal@corenominal.org>
+#    Copyright (C) 2015 damo    <damo@bunsenlabs.org>
+#    Copyright (C) 2015 John Crawley    <john@bunsenlabs.org>
 #
-# Originally written for CrunchBang Linux <http://crunchbang.org/>
-# by Philip Newborough (aka corenominal) <mail@philipnewborough.co.uk>
+#    This program is free software: you can redistribute it and/or modify
+#    it under the terms of the GNU General Public License as published by
+#    the Free Software Foundation, either version 3 of the License, or
+#    (at your option) any later version.
 #
-# Modified by damo <damo@bunsenlabs.org> for BunsenLabs Linux   April 2015
+#    This program is distributed in the hope that it will be useful,
+#    but WITHOUT ANY WARRANTY; without even the implied warranty of
+#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
+#    GNU General Public License for more details.
 #
+#    You should have received a copy of the GNU General Public License
+#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
+
 #   To change the entries shown in the Multimedia pipemenu:
 #   edit ".config/openbox/pipemenus.rc"
-#
-# ---------------------------------------------------------------------
 
 BL_COMMON_LIBDIR='/usr/lib/bunsen/bunsen-common'
 USR_CFG_DIR="$HOME/.config/openbox"
 
-# If the package needs additional configuration before installation
-# create a function called setupappName, it will be called automatically.
-
 if ! . "$BL_COMMON_LIBDIR/bl-include.cfg" 2> /dev/null; then
-    echo $"Error: Failed to locate bl-include.cfg in $BL_COMMON_LIBDIR" >&2
+    echo $"Error: Failed to source bl-include.cfg in $BL_COMMON_LIBDIR" >&2
     exit 1
 elif ! . "$USR_CFG_DIR/pipemenus.rc" 2> /dev/null; then
-    echo $"Error: Failed to locate pipemenus.rc in $USR_CFG_DIR" >&2
+    echo $"Error: Failed to source pipemenus.rc in $USR_CFG_DIR" >&2
     exit 1
 fi
 
@@ -42,6 +47,9 @@ appExists() {
     say "You can try one of these: ${MM_APPS[*]} ${MM_EDITORS[*]} ${MM_UTILS[*]}" 2 >&2
     return 1
 }
+
+# If the package needs additional configuration before installation
+# create a function called setupappName, it will be called automatically.
 
 if [[ $1 = --install ]]; then
     packageName=$2
diff --git a/bin/bl-remote-desktop-pipemenu b/bin/bl-remote-desktop-pipemenu
--- a/bin/bl-remote-desktop-pipemenu
+++ b/bin/bl-remote-desktop-pipemenu
@@ -4,10 +4,28 @@
 # Originally written for CrunchBang Linux <http://crunchbang.org/>
 # by Philip Newborough (aka corenominal) <corenominal@corenominal.org>
 # ---------------------------------------------------------------------
+#    bl-remote-desktop-pipemenu - pipemenu to install remote desktop software
+#    Copyright (C) 2012 Philip Newborough   <corenominal@corenominal.org>
+#    Copyright (C) 2013 Aleks-Daniel Jakimenko
+#    Copyright (C) 2015 John Crawley    <john@bunsenlabs.org>
+#
+#    This program is free software: you can redistribute it and/or modify
+#    it under the terms of the GNU General Public License as published by
+#    the Free Software Foundation, either version 3 of the License, or
+#    (at your option) any later version.
+#
+#    This program is distributed in the hope that it will be useful,
+#    but WITHOUT ANY WARRANTY; without even the implied warranty of
+#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
+#    GNU General Public License for more details.
+#
+#    You should have received a copy of the GNU General Public License
+#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
+
 BL_COMMON_LIBDIR='/usr/lib/bunsen/bunsen-common'
 
 if ! . "$BL_COMMON_LIBDIR/bl-include.cfg" 2> /dev/null; then
-    echo $"Error: Failed to locate bl-include.cfg in $BL_COMMON_LIBDIR" >&2
+    echo $"Error: Failed to source bl-include.cfg in $BL_COMMON_LIBDIR" >&2
     exit 1
 fi
 
@@ -19,7 +37,7 @@ if [[ $1 = --install ]]; then
         ;;
     server)
         terminalCheck -T "Install VNC Server" "$@"
-        promptInstall  'REMOTE DESKTOP SERVER' 'This script will install Vino VNC server.' 'vino'
+        promptInstall  'REMOTE DESKTOP SERVER' 'This script will install Vino VNC server and dconf-editor.' 'vino dconf-editor'
         ;;
     *)
         echo "$0: no such install option $2"
@@ -51,7 +69,7 @@ else
         else
             menuItem 'Start VNC Server' '/usr/lib/vino/vino-server'
         fi
-        menuItem 'VNC Server Preferences' 'vino-preferences'
+        menuItem 'VNC Server Preferences' 'sh -c "notify-send -t 15000 -i \"dialog-info\" \"Configure Vino\" \"In dconf-editor open:\norg -> gnome -> desktop  -> remote-access\" ;dconf-editor"'
     else
         menuItem 'Install VNC Server' "$0 --install server"
     fi
diff --git a/bin/bl-tint2-pipemenu b/bin/bl-tint2-pipemenu
--- a/bin/bl-tint2-pipemenu
+++ b/bin/bl-tint2-pipemenu
@@ -1,7 +1,20 @@
 #!/bin/bash
+
+#    bl-tint2-pipemenu - an Openbox pipemenu for tint2 manipulation
+#    Copyright (C) 2015-2016 damo    <damo@bunsenlabs.org>
 #
-# bl-tint2-pipemenu
-# Written for BunsenLabs Linux by damo <damo@bunsenlabs.org> April 2015
+#    This program is free software: you can redistribute it and/or modify
+#    it under the terms of the GNU General Public License as published by
+#    the Free Software Foundation, either version 3 of the License, or
+#    (at your option) any later version.
+#
+#    This program is distributed in the hope that it will be useful,
+#    but WITHOUT ANY WARRANTY; without even the implied warranty of
+#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
+#    GNU General Public License for more details.
+#
+#    You should have received a copy of the GNU General Public License
+#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 
 BL_COMMON_LIBDIR='/usr/lib/bunsen/bunsen-common'
 
@@ -10,16 +23,16 @@ TINT2RC="$TINT2PATH/tint2rc"
 TZEN="bl-tint2zen"
 
 if ! . "$BL_COMMON_LIBDIR/bl-include.cfg" 2> /dev/null; then
-    echo $"Error: Failed to locate bl-include.cfg in $BL_COMMON_LIBDIR" >&2
+    echo $"Error: Failed to source bl-include.cfg in $BL_COMMON_LIBDIR" >&2
     exit 1
 fi
 
 loadTEditmenu(){
-    menuSeparator 
+    menuSeparator
     menuItem "Default tint2rc" "bl-text-editor $TINT2RC"
     if [ "$(pidof tint2)" ];then
         menuSubmenu "RunningTint2" "Running Tint2s"
-        pgrep -a tint2 | while read pid cmd; do 
+        pgrep -a tint2 | while read pid cmd; do
             if [[ ${cmd%% *} = tint2 ]]; then
                 TINT=${cmd##* }
                 TINT2=${TINT#$HOME/.config/}
@@ -58,5 +71,3 @@ menuItem "Tint2 Chooser" "$TZEN"
 loadRestartmenu
 getTint2s
 menuEnd
-
-
diff --git a/bin/bl-x-www-browser-pipemenu b/bin/bl-x-www-browser-pipemenu
--- a/bin/bl-x-www-browser-pipemenu
+++ b/bin/bl-x-www-browser-pipemenu
@@ -1,31 +1,37 @@
 #!/bin/bash
-# ---------------------------------------------------------------------
-# A pipemenu to install a browser on Bunsen Labs Linux.
+#    bl-x-www-browser-pipemenu - an Openbox pipemenu for web browsers
+#    Copyright (C) 2012 Philip Newborough   <corenominal@corenominal.org>
+#    Copyright (C) 2013 Aleks-Daniel Jakimenko
+#    Copyright (C) 2015 damo    <damo@bunsenlabs.org>
+#    Copyright (C) 2015 John Crawley    <john@bunsenlabs.org>
 #
-# Originally written for CrunchBang Linux <http://crunchbang.org/>
-# by Philip Newborough (aka corenominal) <corenominal@corenominal.org>
+#    This program is free software: you can redistribute it and/or modify
+#    it under the terms of the GNU General Public License as published by
+#    the Free Software Foundation, either version 3 of the License, or
+#    (at your option) any later version.
 #
-# Modified by damo <damo@bunsenlabs.org> for BunsenLabs Linux   April 2015
+#    This program is distributed in the hope that it will be useful,
+#    but WITHOUT ANY WARRANTY; without even the implied warranty of
+#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
+#    GNU General Public License for more details.
 #
+#    You should have received a copy of the GNU General Public License
+#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
+
 #   To change the entries shown in the Browsers pipemenu:
 #   edit ".config/openbox/pipemenus.rc"
-#
-# ---------------------------------------------------------------------
 
 BL_COMMON_LIBDIR='/usr/lib/bunsen/bunsen-common'
 USR_CFG_DIR="$HOME/.config/openbox"
-
-# If the package needs additional configuration before installation
-# create a function called setupBrowserName, it will be called automatically.
 
 KEY_URLS_GOOGLE=('https://dl-ssl.google.com/linux/linux_signing_key.pub')
 KEY_URLS_OPERA=('http://deb.opera.com/archive.key')
 
 if ! . "$BL_COMMON_LIBDIR/bl-include.cfg" 2> /dev/null; then
-    echo $"Error: Failed to locate bl-include.cfg in $BL_COMMON_LIBDIR" >&2
+    echo $"Error: Failed to source bl-include.cfg in $BL_COMMON_LIBDIR" >&2
     exit 1
 elif ! . "$USR_CFG_DIR/pipemenus.rc" 2> /dev/null; then
-    echo $"Error: Failed to locate pipemenus.rc in $USR_CFG_DIR" >&2
+    echo $"Error: Failed to source pipemenus.rc in $USR_CFG_DIR" >&2
     exit 1
 fi
 
@@ -68,6 +74,9 @@ addAptKey() {
     rm -f "$keyFile"
     return 0
 }
+
+# If the package needs additional configuration before installation
+# create a function called setupBrowserName, it will be called automatically.
 
 setupGoogleChromeStable() {
     addAptKey "${KEY_URLS_GOOGLE[@]}" || return 1
