Gracefully handle absence of bunsen-utilities
bl-conky-pipemenu, bl-tint2-pipemenu, bl-kb-pipemenu:
Handle missing commands provided by bunsen-utilities without error.

diff --git a/bin/bl-conky-pipemenu b/bin/bl-conky-pipemenu
--- a/bin/bl-conky-pipemenu
+++ b/bin/bl-conky-pipemenu
@@ -26,32 +26,71 @@ CSESSION="bl-conky-session"
 HELPFILE="/usr/share/bunsen/bunsen-docs/helpfile-conkyzen.txt"
 
 if ! . "$BL_COMMON_LIBDIR/bl-include.cfg" 2> /dev/null; then
-    echo $"Error: Failed to source bl-include.cfg in $BL_COMMON_LIBDIR" >&2
+    echo "Error: Failed to source bl-include.cfg in $BL_COMMON_LIBDIR" >&2
     exit 1
 fi
 if [ ! -e "$CSESSIONFILE" ] 2> /dev/null ; then
-    echo $"Error: Failed to locate conky-sessionfile in $CONKYPATH" >&2
+    echo "Error: Failed to locate conky-sessionfile in $CONKYPATH" >&2
     echo "conky -c $HOME/.conkyrc & sleep 1" > "$CSESSIONFILE"
 fi
 if [ ! -e "$SESSIONS" ] 2> /dev/null ; then
-    echo $"Error: Failed to locate saved-sessions in $CONKYPATH" >&2
+    echo "$0: Failed to locate saved-sessions in $CONKYPATH" >&2
 fi
 
-declareDependencies yad bl-conkyzen bl-conky-session
+declareDependencies yad
 
 getSessions(){  # read any saved sessions from save-sessions file
     menuItem "Default" "$CSESSION $CSESSIONFILE"
-    while read session ;do
-        [[ -z $session ]] && continue   # skip if line is blank
-        menuItem "$session" "$CSESSION $session"
-    done < "$SESSIONS"
+    if [ -e "$SESSIONS" ]
+    then
+        while read session ;do
+            [[ -z $session ]] && continue   # skip if line is blank
+            menuItem "$session" "$CSESSION $session"
+        done < "$SESSIONS"
+    else
+        echo "$0: Failed to locate saved-sessions in $CONKYPATH" >&2
+    fi
 }
 
-loadEditmenu(){
+loadChooserMenu(){
+    if type "$CZEN" &>/dev/null;then  # bl-conkyzen script found
+        menuItem "Conky Chooser" "$CZEN"
+    fi
+}
+
+loadNewsessionMenu(){
+    if type "$CZEN" &>/dev/null;then  # bl-conkyzen script found
+        menuItem "New Conky Session" "$CZEN -z"
+    fi
+}
+
+loadReloadMenu(){
+    if type "$CSESSION" &>/dev/null;then  # bl-conky-session script found
+        menuItem "Reload Conkys" "$CSESSION"
+    fi
+}
+
+loadSavedsessionSubmenu(){
+    if type "$CSESSION" &>/dev/null;then  # bl-conky-session script found
+        menuSubmenu "Sessions" "Saved Sessions"
+        getSessions
+        menuSubmenuEnd
+    fi
+}
+
+loadPinMenu(){
+    if type bl-conkypin &>/dev/null;then
+        menuItem "Pin moveable Conkys" "bl-conkypin"
+        menuSeparator
+    fi
+}
+
+loadEditMenu(){
     menuItem "Default conkyrc" "bl-text-editor $CONKYDEFAULT"
     if [[ $(pidof conky) ]];then
         menuSubmenu "RunningConky" "Running Conkys"
         while read session ;do  # get running conkys from sessionfile
+            [[ -z $session ]] && continue
             CPATH=$(echo "$session" | awk '{print $3}')
             CONKY=$(echo "$CPATH" | awk -F"/" '{print $(NF-1)"/"$NF }')
             menuItem "$CONKY" "bl-text-editor $CPATH"
@@ -64,11 +103,11 @@ loadEditmenu(){
 
 getConkys(){
     menuSubmenu "EditConky" "Edit Conkys"
-        if type bl-conkyedit;then  # bl-conkyedit script found
+        if type bl-conkyedit &>/dev/null;then  # bl-conkyedit script found
             menuItem "Conky Editor" "bl-conkyedit"
-            loadEditmenu
+            loadEditMenu
         else
-            loadEditmenu
+            loadEditMenu
         fi
     menuSubmenuEnd
 }
@@ -86,18 +125,13 @@ checkHelpfile(){
 }
 
 menuStart "Conkymenu" "Conky"
-menuItem "Conky Chooser" "$CZEN"
-menuItem "Reload Conkys" "$CSESSION"
+loadChooserMenu
+loadReloadMenu
 getConkys
 menuSeparator
-menuItem "Pin moveable Conkys" "bl-conkypin"
-menuSeparator
-menuItem "New Conky Session" "bl-conkyzen -z"
-menuSubmenu "Sessions" "Saved Sessions"
-getSessions
-menuSubmenuEnd
+loadPinMenu
+loadNewsessionMenu
+loadSavedsessionSubmenu
 menuSeparator
 checkHelpfile
 menuEnd
-
-
