Rename bl-include.cfg to bl-includes everywhere
bl-conky-pipemenu: Downgrade failure to find conky-sessionfile error to message.
bl-dropbox-pipemenu: Replace python-gpgme with python-gpg.
bl-libreoffice-pipemenu: Replace libreoffice-gtk with libreoffice-gtk2.
bl-printing-pipemenu: Remove gksudo for system-config-printer call.
Update copyright years in modified files
.

diff --git a/bin/bl-conky-pipemenu b/bin/bl-conky-pipemenu
--- a/bin/bl-conky-pipemenu
+++ b/bin/bl-conky-pipemenu
@@ -1,7 +1,7 @@
 #!/bin/bash
 #    bl-conky-pipemenu - an Openbox pipemenu for manipulating conky
 #    Copyright (C) 2015 damo <damo@bunsenlabs.org>
-#                  2016 John Crawley <john@bunsenlabs.org>
+#                  2016-2019 John Crawley <john@bunsenlabs.org>
 #
 #    This program is free software: you can redistribute it and/or modify
 #    it under the terms of the GNU General Public License as published by
@@ -49,12 +49,12 @@ CZEN="bl-conkyzen"
 CSESSION="bl-conky-session"
 HELPFILE="/usr/share/bunsen/docs/helpfile-conkyzen.txt"
 
-if ! . "$BL_COMMON_LIBDIR/bl-include.cfg" 2> /dev/null; then
-    echo "Error: Failed to source bl-include.cfg in $BL_COMMON_LIBDIR" >&2
+if ! . "$BL_COMMON_LIBDIR/bl-includes" 2> /dev/null; then
+    echo "Error: Failed to source bl-includes in $BL_COMMON_LIBDIR" >&2
     exit 1
 fi
 if [ ! -e "$CSESSIONFILE" ] 2> /dev/null ; then
-    echo "Error: Failed to locate conky-sessionfile in $CONKYPATH" >&2
+    echo "Failed to locate ${CSESSIONFILE}, generating default..."
     echo "conky -c $HOME/.conkyrc & sleep 1" > "$CSESSIONFILE"
 fi
 if [ ! -e "$SESSIONS" ] 2> /dev/null ; then
diff --git a/bin/bl-dropbox-pipemenu b/bin/bl-dropbox-pipemenu
--- a/bin/bl-dropbox-pipemenu
+++ b/bin/bl-dropbox-pipemenu
@@ -2,7 +2,7 @@
 #    bl-dropbox-pipemenu: an Openbox pipemenu for use with Dropbox
 #    Copyright (C) 2012 Philip Newborough <corenominal@corenominal.org>
 #    Copyright (C) 2013 Aleks-Daniel Jakimenko
-#    Copyright (C) 2015-2016  John Crawley <john@bunsenlabs.org>
+#    Copyright (C) 2015-2019  John Crawley <john@bunsenlabs.org>
 #
 #    This program is free software: you can redistribute it and/or modify
 #    it under the terms of the GNU General Public License as published by
@@ -61,7 +61,7 @@ PROMPT_DELAY_VARIANTS=(FAlSE 0 FALSE 10 FALSE 20 FALSE 30 FALSE 40 FALSE 50 TRUE
 
 BL_COMMON_LIBDIR='/usr/lib/bunsen/common'
 
-for i in bl-include.cfg yad-includes
+for i in bl-includes yad-includes
 do
     if ! . "$BL_COMMON_LIBDIR/$i" 2> /dev/null; then
         echo "Error: Failed to source $i in $BL_COMMON_LIBDIR" >&2
@@ -114,19 +114,19 @@ elif [[ $1 = '--install-dropbox' ]]; then
         exit 1
     }
 
-    allInstalled python-gpgme || {
-        yad_question 'We need to install the package python-gpgme.\nDo you want to proceed?' || exit 0
+    allInstalled python-gpg || {
+        yad_question 'We need to install the package python-gpg.\nDo you want to proceed?' || exit 0
         tmpDir=$(mktemp -d)
         tmpFile=$(mktemp --tmpdir="$tmpDir")
         export tmpFile
         installer(){
             (
-            say 'Installing python-gpgme...' 1
+            say 'Installing python-gpg...' 1
             connectiontest || return 1
             say 'Updating sources...' 1
             safeUpdate || say 'Continuing in spite of update problems...' 3
             say 'Installing...' 1
-            safeInstall -y python-gpgme || return 1
+            safeInstall -y python-gpg || return 1
             say "
     python-pgpme has been installed successfully.
 
@@ -136,12 +136,12 @@ elif [[ $1 = '--install-dropbox' ]]; then
             )
         }
         export -f say connectiontest errorExit safeUpdate safeInstall installer
-        x-terminal-emulator -T 'Installing python-gpgme' -e bash -c 'installer; echo $? > "$tmpFile"'
+        x-terminal-emulator -T 'Installing python-gpg' -e bash -c 'installer; echo $? > "$tmpFile"'
         instRet=$(<$tmpFile)
         [[ -d $tmpDir && $tmpDir = /tmp/* ]] && rm -r "$tmpDir"
         [[ $instRet -ne 0 ]] && {
-            echo "$0: failed to install python-gpgme." >&2
-            yad_error 'Failed to install python-gpgme.'
+            echo "$0: failed to install python-gpg." >&2
+            yad_error 'Failed to install python-gpg.'
             exit 1
         }
     }
diff --git a/bin/bl-graphics-pipemenu b/bin/bl-graphics-pipemenu
--- a/bin/bl-graphics-pipemenu
+++ b/bin/bl-graphics-pipemenu
@@ -74,8 +74,8 @@ mkdir -p "$SCROTSDIR"
 # user_package_commands might be in $USR_CFG_DIR/pipemenus.rc
 declare -A user_package_commands AppName AppStatus AppCmd
 
-if ! . "$BL_COMMON_LIBDIR/bl-include.cfg" 2> /dev/null; then
-    echo $"Error: Failed to source bl-include.cfg in $BL_COMMON_LIBDIR" >&2
+if ! . "$BL_COMMON_LIBDIR/bl-includes" 2> /dev/null; then
+    echo $"Error: Failed to source bl-includes in $BL_COMMON_LIBDIR" >&2
     exit 1
 fi
 
@@ -121,7 +121,7 @@ nodups(){
     done
 }
 
-# if this function is removed the version in bl-include.cfg will be used
+# if this function is removed the version in bl-includes will be used
 #allInstalled(){
 #    local list="/var/lib/dpkg/info/${1}.list"
 #    [[ -f "${list}" ]] || return 1
diff --git a/bin/bl-kb-pipemenu b/bin/bl-kb-pipemenu
--- a/bin/bl-kb-pipemenu
+++ b/bin/bl-kb-pipemenu
@@ -54,8 +54,8 @@ KBSCRIPT="bl-kb"
 RCPATH="$USR_CFG_DIR/rc.xml"
 KBTEXT="$USR_CFG_DIR/kbinds.txt"
 
-if ! . "$BL_COMMON_LIBDIR/bl-include.cfg" 2> /dev/null; then
-    echo $"Error: Failed to locate bl-include.cfg in $BL_COMMON_LIBDIR" >&2
+if ! . "$BL_COMMON_LIBDIR/bl-includes" 2> /dev/null; then
+    echo $"Error: Failed to locate bl-includes in $BL_COMMON_LIBDIR" >&2
     exit 1
 fi
 
diff --git a/bin/bl-libreoffice-pipemenu b/bin/bl-libreoffice-pipemenu
--- a/bin/bl-libreoffice-pipemenu
+++ b/bin/bl-libreoffice-pipemenu
@@ -2,7 +2,7 @@
 #    bl-libreoffice-pipemenu an Openbox Pipe Menu for use with LibreOffice
 #    Copyright (C) 2012 Philip Newborough   <corenominal@corenominal.org>
 #    Copyright (C) 2013 Aleks-Daniel Jakimenko
-#    Copyright (C) 2015-2017 John Crawley    <john@bunsenlabs.org>
+#    Copyright (C) 2015-2019 John Crawley    <john@bunsenlabs.org>
 #
 #    This program is free software: you can redistribute it and/or modify
 #    it under the terms of the GNU General Public License as published by
@@ -41,8 +41,8 @@ done
 
 BL_COMMON_LIBDIR='/usr/lib/bunsen/common'
 
-if ! . "$BL_COMMON_LIBDIR/bl-include.cfg" 2> /dev/null; then
-    echo $"Error: Failed to locate bl-include.cfg in $BL_COMMON_LIBDIR" >&2
+if ! . "$BL_COMMON_LIBDIR/bl-includes" 2> /dev/null; then
+    echo $"Error: Failed to locate bl-includes in $BL_COMMON_LIBDIR" >&2
     exit 1
 fi
 
@@ -78,12 +78,12 @@ if [[ $1 = --install ]]; then
         appName=${AppName[$packageName]}
         appExists "$packageName" || exit 1
         terminalCheck -T "Install $appName" "$@"
-        if allInstalled libreoffice-gtk; then
+        if allInstalled libreoffice-gtk2; then
             inst_pkgs=( "$packageName" )
             desc="This script will install $appName (without recommends)."
         else
-            inst_pkgs=( "$packageName" 'libreoffice-gtk' )
-            desc="This script will install $appName and libreoffice-gtk (without recommends)."
+            inst_pkgs=( "$packageName" 'libreoffice-gtk2' )
+            desc="This script will install $appName and libreoffice-gtk2 (without recommends)."
         fi
         promptInstall --no-install-recommends "$appName" "$desc" "${inst_pkgs[@]}"
     fi
diff --git a/bin/bl-printing-pipemenu b/bin/bl-printing-pipemenu
--- a/bin/bl-printing-pipemenu
+++ b/bin/bl-printing-pipemenu
@@ -2,7 +2,7 @@
 #    bl-printing-pipemenu an Openbox pipemenu for configuring printing
 #    Copyright (C) 2012 Philip Newborough   <corenominal@corenominal.org>
 #    Copyright (C) 2013 Aleks-Daniel Jakimenko
-#    Copyright (C) 2015 John Crawley    <john@bunsenlabs.org>
+#    Copyright (C) 2015-2019 John Crawley    <john@bunsenlabs.org>
 #
 #    This program is free software: you can redistribute it and/or modify
 #    it under the terms of the GNU General Public License as published by
@@ -41,8 +41,8 @@ done
 
 BL_COMMON_LIBDIR='/usr/lib/bunsen/common'
 
-if ! . "$BL_COMMON_LIBDIR/bl-include.cfg" 2> /dev/null; then
-    echo $"Error: Failed to source bl-include.cfg in $BL_COMMON_LIBDIR" >&2
+if ! . "$BL_COMMON_LIBDIR/bl-includes" 2> /dev/null; then
+    echo $"Error: Failed to source bl-includes in $BL_COMMON_LIBDIR" >&2
     exit 1
 fi
 
@@ -60,7 +60,7 @@ else
     # Pipemenu
     menuStart
     if type 'system-config-printer' &> /dev/null; then
-        menuItem 'Configure Printers' 'gksudo system-config-printer'
+        menuItem 'Configure Printers' 'system-config-printer'
     else
         menuItem 'Install Printing Support' "$0 --install"
     fi
diff --git a/bin/bl-tint2-pipemenu b/bin/bl-tint2-pipemenu
--- a/bin/bl-tint2-pipemenu
+++ b/bin/bl-tint2-pipemenu
@@ -46,8 +46,8 @@ TINT2PATH="$HOME/.config/tint2"
 TINT2RC="$TINT2PATH/tint2rc"
 TZEN="bl-tint2zen"
 
-if ! . "$BL_COMMON_LIBDIR/bl-include.cfg" 2> /dev/null; then
-    echo $"Error: Failed to source bl-include.cfg in $BL_COMMON_LIBDIR" >&2
+if ! . "$BL_COMMON_LIBDIR/bl-includes" 2> /dev/null; then
+    echo $"Error: Failed to source bl-includes in $BL_COMMON_LIBDIR" >&2
     exit 1
 fi
 
