Make pipemenus.rc optional
bl-multimedia-pipemenu, bl-graphics-pipemenu: merge optional app lists
 from ~/.config/openbox/pipemenus.rc to default lists.
 Allow packages to use commands different from package names.
 Detect BL alternatives apps and mark as such on menus.
bl-help-pipemenu: add link to forum "Getting Started" section.
bl-libreoffice-pipemenu: install libreoffice-gtk if necessary.

diff --git a/bin/bl-graphics-pipemenu b/bin/bl-graphics-pipemenu
--- a/bin/bl-graphics-pipemenu
+++ b/bin/bl-graphics-pipemenu
@@ -2,7 +2,7 @@
 #    bl-graphics-pipemenu - an Openbox pipemenu for Graphics applications
 #    Copyright (C) 2012 Philip Newborough   <corenominal@corenominal.org>
 #    Copyright (C) 2015-2016 damo    <damo@bunsenlabs.org>
-#    Copyright (C) 2015-2016 John Crawley    <john@bunsenlabs.org>
+#    Copyright (C) 2015-2017 John Crawley    <john@bunsenlabs.org>
 #
 #    This program is free software: you can redistribute it and/or modify
 #    it under the terms of the GNU General Public License as published by
@@ -17,7 +17,7 @@
 #    You should have received a copy of the GNU General Public License
 #    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 
-#   To change the entries shown in the Graphics pipemenu:
+#   To add to the entries shown in the Graphics pipemenu:
 #   edit ".config/openbox/pipemenus.rc"
 
 HELP='    bl-graphics-pipemenu an Openbox Pipe Menu for graphics applications
@@ -26,7 +26,8 @@ HELP='    bl-graphics-pipemenu an Openbox Pipe Menu for graphics applications
 Options (usually passed from the menu):
     -h --help   show this message
     --install   install a graphics-related package
-    (the package must be in the list defined in the pipemenu config file)
+    (the package must be in the list defined in the pipemenu config file
+    or in the default list in this file)
 
     If bl-graphics-pipemenu is called with no options (the usual method),
     it will output an xml openbox pipemenu
@@ -34,6 +35,16 @@ Options (usually passed from the menu):
 
 See ~/.config/openbox/pipemenus.rc for configuration options.
 '
+# default apps lists
+# user lists in ~/.config/openbox/pipemenus.rc will be merged
+DEF_GRAPHICS_APPS=( 'mirage' 'gpicview' 'ristretto' 'viewnior' 'eog' 'gimp' 'blender' 'inkscape' 'mandelbulber' )
+DEF_GRAPHICS_SCROTS=('xfce4-screenshooter' 'scrot' )
+
+# array: commands in menu which are different from package names
+declare -A pkg_cmd
+pkg_cmd=()
+########################################################################
+
 # look for a help option somewhere
 for i in "$@"
 do
@@ -58,19 +69,75 @@ fi
 SCROTSDIR="$IMGDIR/screenshots"
 mkdir -p "$SCROTSDIR"
 
+# user_package_commands might be in $USR_CFG_DIR/pipemenus.rc
+declare -A user_package_commands AppName AppStatus AppCmd
+
 if ! . "$BL_COMMON_LIBDIR/bl-include.cfg" 2> /dev/null; then
     echo $"Error: Failed to source bl-include.cfg in $BL_COMMON_LIBDIR" >&2
     exit 1
 elif ! . "$USR_CFG_DIR/pipemenus.rc" 2> /dev/null; then
-    echo $"Error: Failed to source pipemenus.rc in $USR_CFG_DIR" >&2
-    exit 1
+    echo $"Failed to source pipemenus.rc in $USR_CFG_DIR" >&2
 fi
 
-declare -A AppName AppStatus # AppName: split on hyphens, first letter uppercase
+# add any user-specified commands, overwriting defaults if set
+for i in "${!user_package_commands[@]}"
+do
+    [[ -n ${user_package_commands[$i]} ]] || continue
+    pkg_cmd[$i]="${user_package_commands[$i]}"
+done
+
+# get BL alternatives viewer
+bl_iv_cmd=$(readlink -f /usr/bin/bl-image-viewer)
+bl_iv_cmd="${bl_iv_cmd##*/}"
+BL_VIEWER=
+for i in "${DEF_GRAPHICS_APPS[@]}" "${GRAPHICS_APPS[@]-}"
+do
+    [[ ${pkg_cmd[$i]:-$i} = "$bl_iv_cmd" ]] && {
+        BL_VIEWER=$i
+        # AppName: split on hyphens, first letter uppercase
+        words=(${i//-/ })
+        AppName[$i]="${words[*]^} Image Viewer"
+        break
+    }
+done
+
+# remove duplicate members of array passed as $1, keep order
+nodups(){
+    local -A check
+    local -n target_array="$1"
+    for i in "${!target_array[@]}"
+    do
+        local content="${target_array[$i]}"
+        if [[ ${check[$content]+x} = x ]]
+        then
+            unset target_array[$i]
+        else
+            check[$content]=1
+        fi
+    done
+}
+
+# if this function is removed the version in bl-include.cfg will be used
+allInstalled(){
+    local list="/var/lib/dpkg/info/${1}.list"
+    [[ -f "${list}" ]] || return 1
+    grep -Evq '^/etc($|/)' "${list}" || return 1
+    return 0
+}
+
+GRAPHICS_APPS=( "$BL_VIEWER" "${DEF_GRAPHICS_APPS[@]}" "${GRAPHICS_APPS[@]-}" )
+GRAPHICS_SCROTS=( "${DEF_GRAPHICS_SCROTS[@]}" "${GRAPHICS_SCROTS[@]-}" )
+
+for i in GRAPHICS_APPS GRAPHICS_SCROTS
+do
+    nodups "$i"
+done
+
 for curApp in "${GRAPHICS_APPS[@]}" "${GRAPHICS_SCROTS[@]}"; do
     words=(${curApp//-/ })
-    AppName[$curApp]="${words[*]^}"
-    type "$curApp" >/dev/null 2>&1 && AppStatus[$curApp]=installed
+    AppName[$curApp]="${AppName[$curApp]:-${words[*]^}}"
+    AppCmd[$curApp]="${pkg_cmd[$curApp]:-$curApp}" # use packagename as command if not defined in pkg_cmd
+    allInstalled "$curApp" && AppStatus[$curApp]='installed' || AppStatus[$curApp]=''
 done
 
 appExists() {
@@ -123,17 +190,13 @@ if [[ $1 = --install ]]; then
     desc="This script will install $appName."
     setupFunctionName="setup${appName//[^a-zA-Z]/}" # setupFunctionName should now be in format like 'setupBlender'
     if [[ $(type -t "$setupFunctionName") = 'function' ]]; then
-            promptInstall --setup "$setupFunctionName" "$appName" "$desc" "$packageName"
+        promptInstall --setup "$setupFunctionName" "$appName" "$desc" "$packageName"
     else
-        if [[ $packageName = gimp ]];then
-            if ! prompt 'This will install GIMP. Do you also want to install Gimp Extras?' N;then
-                promptInstall "$appName" "$desc" "$packageName"
-            else
-                appName="Gimp and Gimp Extras"
-                packageNameSet=(gimp gimp-plugin-registry gimp-gmic)
-                desc="This script will install gimp, gimp-plugin-registry and gimp-gmic"
-                promptInstall "$appName" "$desc" "${packageNameSet[@]}"
-            fi
+        if [[ $packageName = gimp ]] && prompt 'This will install GIMP. Do you also want to install Gimp Extras?' N; then
+            appName="Gimp and Gimp Extras"
+            packageNameSet=(gimp gimp-plugin-registry gimp-gmic)
+            desc="This script will install gimp, gimp-plugin-registry and gimp-gmic"
+            promptInstall "$appName" "$desc" "${packageNameSet[@]}"
         else
             promptInstall "$appName" "$desc" "$packageName"
         fi
@@ -150,16 +213,8 @@ else # pipemenu
             menuItem "${AppName[$curApp]}" "$curApp"
         fi
     done
-    menu_started=false
-    for curApp in "${GRAPHICS_APPS[@]}"; do
-        if ! [[ ${AppStatus[$curApp]} = installed ]]; then
-            $menu_started || menuSubmenu "graph-apps-install-submenu" "Install"
-            menu_started=true
-            menuItem "Install ${AppName[$curApp]}" "$0 --install $curApp"
-        fi
-    done
-    $menu_started && menuSubmenuEnd
 
+    menuSeparator
     menuSeparator 'Screenshots'
 
     for curScrot in "${GRAPHICS_SCROTS[@]}"; do
@@ -171,15 +226,30 @@ else # pipemenu
             fi
         fi
     done
-    menu_started=false
+
+    install_menu_started=false
+
+    for curApp in "${GRAPHICS_APPS[@]}"; do
+        if ! [[ ${AppStatus[$curApp]} = installed ]]; then
+            $install_menu_started || { menuSeparator; menuSubmenu "graph-install-submenu" "Install";}
+            install_menu_started=true
+            menuItem "Install ${AppName[$curApp]}" "$0 --install $curApp"
+        fi
+    done
+
+    scrots_menu_started=false
     for curScrot in "${GRAPHICS_SCROTS[@]}"; do
         if ! [[ ${AppStatus[$curScrot]} = installed ]]; then
-            $menu_started || menuSubmenu "graph-scrots-install-submenu" "Install"
-            menu_started=true
+            $install_menu_started || { menuSeparator; menuSubmenu "graph-install-submenu" "Install";}
+            $scrots_menu_started || menuSeparator 'Screenshots'
+            install_menu_started=true
+            scrots_menu_started=true
             menuItem "Install ${AppName[$curScrot]}" "$0 --install $curScrot"
         fi
     done
-    $menu_started && menuSubmenuEnd
+
+    $install_menu_started && menuSubmenuEnd
+
     menuEnd
 fi
 exit 0
diff --git a/bin/bl-multimedia-pipemenu b/bin/bl-multimedia-pipemenu
--- a/bin/bl-multimedia-pipemenu
+++ b/bin/bl-multimedia-pipemenu
@@ -2,7 +2,7 @@
 #    bl-multimedia-pipemenu - an Openbox pipemenu for Multimedia applications
 #    Copyright (C) 2012 Philip Newborough   <corenominal@corenominal.org>
 #    Copyright (C) 2015 damo    <damo@bunsenlabs.org>
-#    Copyright (C) 2015 John Crawley    <john@bunsenlabs.org>
+#    Copyright (C) 2015-2017 John Crawley    <john@bunsenlabs.org>
 #
 #    This program is free software: you can redistribute it and/or modify
 #    it under the terms of the GNU General Public License as published by
@@ -17,7 +17,7 @@
 #    You should have received a copy of the GNU General Public License
 #    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 
-#   To change the entries shown in the Multimedia pipemenu:
+#   To add to the entries shown in the Multimedia pipemenu:
 #   edit ".config/openbox/pipemenus.rc"
 
 HELP='    bl-multimedia-pipemenu an Openbox Pipe Menu for multimedia applications
@@ -26,7 +26,8 @@ HELP='    bl-multimedia-pipemenu an Openbox Pipe Menu for multimedia application
 Options (usually passed from the menu):
     -h --help   show this message
     --install   install a multimedia package
-    (the package must be in the list defined in the pipemenu config file)
+    (the package must be in the list defined in the pipemenu config file
+     or in the default list in this file)
 
     If bl-multimedia-pipemenu is called with no options (the usual method),
     it will output an xml openbox pipemenu
@@ -34,6 +35,18 @@ Options (usually passed from the menu):
 
 See ~/.config/openbox/pipemenus.rc for configuration options.
 '
+
+# default apps lists
+# user lists in ~/.config/openbox/pipemenus.rc will be merged
+DEF_MM_APPS=('mpv' 'vlc' 'audacious' 'smplayer' 'gnome-mplayer')
+DEF_MM_EDITORS=('mhwaveedit' 'audacity' 'openshot')
+DEF_MM_UTILS=('xfburn' 'gtk-recordmydesktop')
+
+# array: commands in menu which are different from package names
+declare -A pkg_cmd
+pkg_cmd=([mpv]='bl-mpv')
+########################################################################
+
 # look for a help option somewhere
 for i in "$@"
 do
@@ -48,19 +61,76 @@ done
 BL_COMMON_LIBDIR='/usr/lib/bunsen/common'
 USR_CFG_DIR="$HOME/.config/openbox"
 
+# user_package_commands might be in $USR_CFG_DIR/pipemenus.rc
+declare -A user_package_commands AppName AppStatus AppCmd
+
 if ! . "$BL_COMMON_LIBDIR/bl-include.cfg" 2> /dev/null; then
-    echo $"Error: Failed to source bl-include.cfg in $BL_COMMON_LIBDIR" >&2
+    echo "Error: Failed to source bl-include.cfg in $BL_COMMON_LIBDIR" >&2
     exit 1
 elif ! . "$USR_CFG_DIR/pipemenus.rc" 2> /dev/null; then
-    echo $"Error: Failed to source pipemenus.rc in $USR_CFG_DIR" >&2
-    exit 1
+    echo "Failed to source pipemenus.rc in $USR_CFG_DIR" >&2
 fi
 
-declare -A AppName AppStatus # AppName: split on hyphens, first letter uppercase
+# add any user-specified commands, overwriting defaults if set
+for i in "${!user_package_commands[@]}"
+do
+    [[ -n ${user_package_commands[$i]} ]] || continue
+    pkg_cmd[$i]="${user_package_commands[$i]}"
+done
+
+# get BL alternatives player
+bl_mp_cmd=$(readlink -f /usr/bin/bl-media-player)
+bl_mp_cmd="${bl_mp_cmd##*/}"
+BL_MM_APP=
+for i in "${DEF_MM_APPS[@]}" "${MM_APPS[@]-}"
+do
+    [[ ${pkg_cmd[$i]:-$i} = "$bl_mp_cmd" ]] && {
+        BL_MM_APP=$i
+        # AppName: split on hyphens, first letter uppercase
+        words=(${i//-/ })
+        AppName[$i]="${words[*]^} Media Player"
+        break
+    }
+done
+
+# remove duplicate, and null, values of array passed as $1, keep order
+nodups(){
+    local -A check
+    local -n target_array="$1"
+    for i in "${!target_array[@]}"
+    do
+        local value="${target_array[$i]}"
+        if [[ -z $value || ${check[$value]+x} = x ]]
+        then
+            unset target_array[$i]
+        else
+            check[$value]=1
+        fi
+    done
+}
+
+# if this function is removed the version in bl-include.cfg will be used
+allInstalled(){
+    local list="/var/lib/dpkg/info/${1}.list"
+    [[ -f "${list}" ]] || return 1
+    grep -Evq '^/etc($|/)' "${list}" || return 1
+    return 0
+}
+
+MM_APPS=( "$BL_MM_APP" "${DEF_MM_APPS[@]}" "${MM_APPS[@]-}" )
+MM_EDITORS=( "${DEF_MM_EDITORS[@]}" "${MM_EDITORS[@]-}" )
+MM_UTILS=( "${DEF_MM_UTILS[@]}" "${MM_UTILS[@]-}" )
+
+for i in MM_APPS MM_EDITORS MM_UTILS
+do
+    nodups "$i"
+done
+
 for curApp in "${MM_APPS[@]}" "${MM_EDITORS[@]}" "${MM_UTILS[@]}"; do
     words=(${curApp//-/ })
-    AppName[$curApp]="${words[*]^}"
-    type "$curApp" >/dev/null 2>&1 && AppStatus[$curApp]=installed
+    AppName[$curApp]="${AppName[$curApp]:-${words[*]^}}"
+    AppCmd[$curApp]="${pkg_cmd[$curApp]:-$curApp}" # use packagename as command if not defined in pkg_cmd
+    allInstalled "$curApp" && AppStatus[$curApp]='installed' || AppStatus[$curApp]=''
 done
 
 appExists() {
@@ -76,7 +146,7 @@ appExists() {
 # If the package needs additional configuration before installation
 # create a function called setupappName, it will be called automatically.
 
-if [[ $1 = --install ]]; then
+if [[ ${1-} = --install ]]; then
     packageName=$2
     appName=${AppName[$packageName]}
     appExists "$packageName" || exit 1
@@ -91,7 +161,7 @@ if [[ $1 = --install ]]; then
         promptInstall "$appName" "$desc" "$packageName"
     fi
 
-elif [[ $1 ]]; then
+elif [[ ${1-} ]]; then
     echo "$0: no such option $*" >&2
     exit 1
 
@@ -100,56 +170,59 @@ else # pipemenu
 
     for curApp in "${MM_APPS[@]}"; do
         if [[ ${AppStatus[$curApp]} = installed ]]; then
-            if [[ "$curApp" = "mpv" ]];then # notify user that mpv is a cli application
-                menuItem "mpv (cli)" "notify-send -t 3000 'mpv is a commandline application'"
-            else
-                menuItem "${AppName[$curApp]}" "$curApp"
-            fi
+            menuItem "${AppName[$curApp]}" "${AppCmd[$curApp]}"
         fi
     done
-    menu_started=false
-    for curApp in "${MM_APPS[@]}"; do
-        if ! [[ ${AppStatus[$curApp]} = installed ]]; then
-            $menu_started || menuSubmenu "mm-apps-install-submenu" "Install"
-            menu_started=true
-            menuItem "Install ${AppName[$curApp]}" "$0 --install $curApp"
-        fi
-    done
-    $menu_started && menuSubmenuEnd
 
     menuSeparator
     menuSeparator 'Editors'
     for curApp in "${MM_EDITORS[@]}"; do
         if [[ ${AppStatus[$curApp]} = installed ]]; then
-            menuItem "${AppName[$curApp]}" "$curApp"
+            menuItem "${AppName[$curApp]}" "${AppCmd[$curApp]}"
         fi
     done
-    menu_started=false
-    for curApp in "${MM_EDITORS[@]}"; do
-        if ! [[ ${AppStatus[$curApp]} = installed ]]; then
-            $menu_started || menuSubmenu "mm-editors-install-submenu" "Install"
-            menu_started=true
-            menuItem "Install ${AppName[$curApp]}" "$0 --install $curApp"
-        fi
-    done
-    $menu_started && menuSubmenuEnd
 
     menuSeparator
     menuSeparator 'Utilities'
     for curApp in "${MM_UTILS[@]}"; do
         if [[ ${AppStatus[$curApp]} = installed ]]; then
-            menuItem "${AppName[$curApp]}" "$curApp"
+            menuItem "${AppName[$curApp]}" "${AppCmd[$curApp]}"
         fi
     done
-    menu_started=false
-    for curApp in "${MM_UTILS[@]}"; do
+
+    install_menu_started=false
+
+    for curApp in "${MM_APPS[@]}"; do
         if ! [[ ${AppStatus[$curApp]} = installed ]]; then
-            $menu_started || menuSubmenu "mm-utils-install-submenu" "Install"
-            menu_started=true
+            $install_menu_started || { menuSeparator; menuSubmenu "mm-install-submenu" "Install";}
+            install_menu_started=true
             menuItem "Install ${AppName[$curApp]}" "$0 --install $curApp"
         fi
     done
-    $menu_started && menuSubmenuEnd
+
+    editors_menu_started=false
+    for curApp in "${MM_EDITORS[@]}"; do
+        if ! [[ ${AppStatus[$curApp]} = installed ]]; then
+            $install_menu_started || { menuSeparator; menuSubmenu "mm-install-submenu" "Install";}
+            $editors_menu_started || menuSeparator 'Editors'
+            install_menu_started=true
+            editors_menu_started=true
+            menuItem "Install ${AppName[$curApp]}" "$0 --install $curApp"
+        fi
+    done
+
+    utils_menu_started=false
+    for curApp in "${MM_UTILS[@]}"; do
+        if ! [[ ${AppStatus[$curApp]} = installed ]]; then
+            $install_menu_started || { menuSeparator; menuSubmenu "mm-install-submenu" "Install";}
+            $utils_menu_started || menuSeparator 'Utilities'
+            install_menu_started=true
+            utils_menu_started=true
+            menuItem "Install ${AppName[$curApp]}" "$0 --install $curApp"
+        fi
+    done
+
+    $install_menu_started && menuSubmenuEnd
 
     menuEnd
 fi
