Change path to bl-include.cfg as it is no longer in /usr/bin The file is now in the bunsen-common package, and currently installed to /usr/lib/bunsen/bunsen-common.

diff --git a/bl-compositor b/bl-compositor
--- a/bl-compositor
+++ b/bl-compositor
@@ -7,8 +7,10 @@
 
 RESTART_ATTEMPTS=20
 
-if ! . bl-include.cfg 2> /dev/null; then
-    echo '  Failed to locate bl-include.cfg in PATH' >&2
+BL_COMMON_LIBDIR='/usr/lib/bunsen/bunsen-common'
+
+if ! . "$BL_COMMON_LIBDIR/bl-include.cfg" 2> /dev/null; then
+    echo $"Error: Failed to locate bl-include.cfg in $BL_COMMON_LIBDIR" >&2
     exit 1
 fi
 
@@ -28,7 +30,7 @@ if [[ $1 = '--edit' ]]; then
     else
         terminator --command='nano "$HOME/.config/compton.conf"'
     fi
-elif [[ $1 = '--toggle' || $1 = '--start' ]]; then # Toggle compositing with compton. 
+elif [[ $1 = '--toggle' || $1 = '--start' ]]; then # Toggle compositing with compton.
     # TODO why --toggle and --start act exactly the same?
     if ! pidof compton > /dev/null; then
         $EXECXCOMP &
diff --git a/bl-dropbox-pipemenu b/bl-dropbox-pipemenu
--- a/bl-dropbox-pipemenu
+++ b/bl-dropbox-pipemenu
@@ -5,6 +5,8 @@
 # by Philip Newborough (aka corenominal) <mail@philipnewborough.co.uk>
 # --------------------------------------------------------------------
 
+BL_COMMON_LIBDIR='/usr/lib/bunsen/bunsen-common'
+
 PROMPT_DELAY_TEXT='It is a good idea to add a delay before autostarting Dropbox
 so that your system can establish a working network connection.
 
@@ -14,9 +16,8 @@ PROMPT_DELAY_VARIANTS=(FALSE 10 FALSE 20 FALSE 30 FALSE 40 FALSE 50 TRUE 60)
 
 USERDBDIR="$HOME/.dropbox-dist/"
 
-
-if ! . bl-include.cfg 2> /dev/null; then
-    echo '  Failed to locate bl-include.cfg in PATH' >&2
+if ! . "$BL_COMMON_LIBDIR/bl-include.cfg" 2> /dev/null; then
+    echo $"Error: Failed to locate bl-include.cfg in $BL_COMMON_LIBDIR" >&2
     exit 1
 fi
 
diff --git a/bl-help-pipemenu b/bl-help-pipemenu
--- a/bl-help-pipemenu
+++ b/bl-help-pipemenu
@@ -1,6 +1,9 @@
 #!/bin/bash
-if ! . bl-include.cfg 2> /dev/null; then
-    echo '  Failed to locate bl-include.cfg in PATH' >&2
+
+BL_COMMON_LIBDIR='/usr/lib/bunsen/bunsen-common'
+
+if ! . "$BL_COMMON_LIBDIR/bl-include.cfg" 2> /dev/null; then
+    echo $"Error: Failed to locate bl-include.cfg in $BL_COMMON_LIBDIR" >&2
     exit 1
 fi
 
diff --git a/bl-remote-desktop-pipemenu b/bl-remote-desktop-pipemenu
--- a/bl-remote-desktop-pipemenu
+++ b/bl-remote-desktop-pipemenu
@@ -4,9 +4,10 @@
 # Originally written for CrunchBang Linux <http://crunchbang.org/>
 # by Philip Newborough (aka corenominal) <corenominal@corenominal.org>
 # ---------------------------------------------------------------------
+BL_COMMON_LIBDIR='/usr/lib/bunsen/bunsen-common'
 
-if ! . bl-include.cfg 2> /dev/null; then
-    echo '  Failed to locate bl-include.cfg in PATH' >&2
+if ! . "$BL_COMMON_LIBDIR/bl-include.cfg" 2> /dev/null; then
+    echo $"Error: Failed to locate bl-include.cfg in $BL_COMMON_LIBDIR" >&2
     exit 1
 fi
 
diff --git a/bl-x-www-browser-pipemenu b/bl-x-www-browser-pipemenu
--- a/bl-x-www-browser-pipemenu
+++ b/bl-x-www-browser-pipemenu
@@ -5,6 +5,7 @@
 # by Philip Newborough (aka corenominal) <corenominal@corenominal.org>
 # ---------------------------------------------------------------------
 
+BL_COMMON_LIBDIR='/usr/lib/bunsen/bunsen-common'
 
 # In order to add another browser, simply add it to this array:
 TOOLS=('chromium' 'iceweasel' 'google-chrome' 'opera')
@@ -13,8 +14,8 @@ TOOLS=('chromium' 'iceweasel' 'google-chrome' 'opera')
 KEY_URLS_GOOGLE=('https://dl-ssl.google.com/linux/linux_signing_key.pub' 'http://packages.crunchbang.org/waldorf-files/apt-keys/google-chrome.key')
 KEY_URLS_OPERA=('http://deb.opera.com/archive.key' 'http://packages.crunchbang.org/waldorf-files/apt-keys/opera.key')
 
-if ! . bl-include.cfg 2> /dev/null; then
-    say 'Failed to locate bl-include.cfg in PATH' >&2
+if ! . "$BL_COMMON_LIBDIR/bl-include.cfg" 2> /dev/null; then
+    echo $"Error: Failed to locate bl-include.cfg in $BL_COMMON_LIBDIR" >&2
     exit 1
 fi
 
