Change to bl- alternatives

diff --git a/bl-graphics-pipemenu b/bl-graphics-pipemenu
--- a/bl-graphics-pipemenu
+++ b/bl-graphics-pipemenu
@@ -7,8 +7,8 @@
 #
 # Modified by <damo> for BunsenLabs Linux   April 2015
 #
-# 	To change the entries shown in the Graphics pipemenu:
-# 	edit ".config/openbox/pipemenus.rc"
+#   To change the entries shown in the Graphics pipemenu:
+#   edit ".config/openbox/pipemenus.rc"
 #
 # ---------------------------------------------------------------------
 
@@ -21,111 +21,111 @@ USR_CFG='.config/openbox/pipemenus.rc'
 #if test -f "/usr/bin/xdg-user-dir";then
 
 if type xdg-user-dir &>/dev/null; then
-	IMGDIR=$(xdg-user-dir PICTURES)
+    IMGDIR=$(xdg-user-dir PICTURES)
 else
-	IMGDIR="~/Pictures"
+    IMGDIR="~/Pictures"
 fi
 # test for screenshots dir, create if it doesn't exist
 SCROTSDIR="$IMGDIR/screenshots"
 if ! [[ -d $SCROTSDIR ]];then
-	mkdir "$SCROTSDIR"
+    mkdir "$SCROTSDIR"
 fi
 
 # If the package needs additional configuration before installation
 # create a function called setupappName, it will be called automatically.
 
 if ! . "$BL_COMMON_LIBDIR/bl-include.cfg" 2> /dev/null; then
-	echo $"Error: Failed to locate bl-include.cfg in $BL_COMMON_LIBDIR" >&2
-	exit 1
+    echo $"Error: Failed to locate bl-include.cfg in $BL_COMMON_LIBDIR" >&2
+    exit 1
 elif ! . "$USR_CFG" 2> /dev/null; then
-	echo $"Error: Failed to locate pipemenus.rc in $USR_CFG" >&2
-	exit 1
+    echo $"Error: Failed to locate pipemenus.rc in $USR_CFG" >&2
+    exit 1
 fi
 
 appExists() {
 
-	for curApp in "${GRAPHICS_APPS[@]}"; do # if $packageName exists in tools array
-		[[ $curApp = "$1" ]] &&
-			return 0
-	done
-	say "Unable to install $1. There is no such application that I know of." 1 >&2
-	say "You can try one of these: ${GRAPHICS_APPS[*]}" 2 >&2
-	return 1
+    for curApp in "${GRAPHICS_APPS[@]}"; do # if $packageName exists in tools array
+        [[ $curApp = "$1" ]] &&
+            return 0
+    done
+    say "Unable to install $1. There is no such application that I know of." 1 >&2
+    say "You can try one of these: ${GRAPHICS_APPS[*]}" 2 >&2
+    return 1
 }
 
 screenshooterExists() {
-	for curScrot in "${GRAPHICS_SCROTS[@]}"; do # if $packageName exists in scrots array
-		[[ $curScrot = "$1" ]] &&
-			return 0
-	done
-	say "Unable to install $1. There is no such application that I know of." 1 >&2
-	say "You can try one of these: ${GRAPHICS_SCROTS[*]}" 2 >&2
-	return 1
+    for curScrot in "${GRAPHICS_SCROTS[@]}"; do # if $packageName exists in scrots array
+        [[ $curScrot = "$1" ]] &&
+            return 0
+    done
+    say "Unable to install $1. There is no such application that I know of." 1 >&2
+    say "You can try one of these: ${GRAPHICS_SCROTS[*]}" 2 >&2
+    return 1
 }
 
-writeScrot() {					# Write scrot submenu items
-	IMG="$SCROTSDIR/%F-%H-%M-%S_scrot.png"
-	VIEW="'bl-image-viewer $IMG'"
-	menuSubmenu 'scrot' 'scrot Screenshooter'
-		menuItem "scrot Now" "scrot $IMG -e $VIEW"
-		menuItem "scrot In 5 secs..." "scrot -d 5 $IMG -e $VIEW"
-		menuItem "scrot In 10 secs" "scrot -d 10 $IMG -e $VIEW"
-		menuItem "scrot Select Area.." "scrot -s $IMG -e $VIEW"
-		menuItem "scrot Current Focus.." "scrot -u $IMG -e $VIEW"
-		menuItem "scrot multi-monitor" "scrot -m $IMG -e $VIEW"
-	menuSubmenuEnd
+writeScrot() {                  # Write scrot submenu items
+    IMG="$SCROTSDIR/%F-%H-%M-%S_scrot.png"
+    VIEW="'bl-image-viewer $IMG'"
+    menuSubmenu 'scrot' 'scrot Screenshooter'
+        menuItem "scrot Now" "scrot $IMG -e $VIEW"
+        menuItem "scrot In 5 secs..." "scrot -d 5 $IMG -e $VIEW"
+        menuItem "scrot In 10 secs" "scrot -d 10 $IMG -e $VIEW"
+        menuItem "scrot Select Area.." "scrot -s $IMG -e $VIEW"
+        menuItem "scrot Current Focus.." "scrot -u $IMG -e $VIEW"
+        menuItem "scrot multi-monitor" "scrot -m $IMG -e $VIEW"
+    menuSubmenuEnd
 }
 
 if [[ $1 && ! $1 = --install-* ]]; then
-	packageName=${1#--}
-	read -ra words <<< "${packageName//-/ }"
-	x-terminal-emulator -T "Install ${words[*]^}" -e "$0" "--install-$packageName"
+    packageName=${1#--}
+    read -ra words <<< "${packageName//-/ }"
+    x-terminal-emulator -T "Install ${words[*]^}" -e "$0" "--install-$packageName"
 
 elif [[ $1 = --install-* ]]; then
-	packageName=${1#--install-}
-	if [[ $1 = --install-scrot ]] || [[ $1 = --install-xfce4-screenshooter ]];then
-		screenshooterExists "$packageName" || exit 1
-	else
-		appExists "$packageName" || exit 1
-	fi
-	appName=${packageName//-/ }
-	read -ra words <<< "$appName"
-	appName=${words[*]^}
-	appNameUpper=${appName^^}
+    packageName=${1#--install-}
+    if [[ $1 = --install-scrot ]] || [[ $1 = --install-xfce4-screenshooter ]];then
+        screenshooterExists "$packageName" || exit 1
+    else
+        appExists "$packageName" || exit 1
+    fi
+    appName=${packageName//-/ }
+    read -ra words <<< "$appName"
+    appName=${words[*]^}
+    appNameUpper=${appName^^}
 
-	setupFunctionName="setup${appName//[^a-zA-Z]/}" # setupFunctionName should now be in format like 'setupBlender'
-	if [[ $(type -t "$setupFunctionName") = 'function' ]]; then
-		promptInstall --setup "$setupFunctionName" "${appNameUpper% APP} APP" "$appName" "$packageName"
-	else
-		promptInstall "${appNameUpper% APP} APP" "$appName" "$packageName"
-	fi
+    setupFunctionName="setup${appName//[^a-zA-Z]/}" # setupFunctionName should now be in format like 'setupBlender'
+    if [[ $(type -t "$setupFunctionName") = 'function' ]]; then
+        promptInstall --setup "$setupFunctionName" "${appNameUpper% APP} APP" "$appName" "$packageName"
+    else
+        promptInstall "${appNameUpper% APP} APP" "$appName" "$packageName"
+    fi
 
 else # pipemenu
-	menuStart
-	for curApp in "${GRAPHICS_APPS[@]}"; do
-		read -ra words <<< "${curApp//-/ }"
-		curAppName=${words[*]^}
-		if type "$curApp" &> /dev/null; then
-			menuItem "$curAppName" "$curApp"
-		else
-			menuItem "Install $curAppName" "$0 --$curApp"
-		fi
-	done
-	menuSeparator 'Screenshots'
+    menuStart
+    for curApp in "${GRAPHICS_APPS[@]}"; do
+        read -ra words <<< "${curApp//-/ }"
+        curAppName=${words[*]^}
+        if type "$curApp" &> /dev/null; then
+            menuItem "$curAppName" "$curApp"
+        else
+            menuItem "Install $curAppName" "$0 --$curApp"
+        fi
+    done
+    menuSeparator 'Screenshots'
 
-	for curScrot in "${GRAPHICS_SCROTS[@]}"; do
-		read -ra words <<< "${curScrot//-/ }"
-		curScrotName=${words[*]^}
-		if type "$curScrot" &> /dev/null; then
-			if [[ "$curScrot" = scrot ]];then
-				writeScrot
-			else
-				menuItem "$curScrotName" "$curScrot"
-			fi
-		else
-			menuItem "Install $curScrotName" "$0 --$curScrot"
-		fi
-	done
-	menuEnd
+    for curScrot in "${GRAPHICS_SCROTS[@]}"; do
+        read -ra words <<< "${curScrot//-/ }"
+        curScrotName=${words[*]^}
+        if type "$curScrot" &> /dev/null; then
+            if [[ "$curScrot" = scrot ]];then
+                writeScrot
+            else
+                menuItem "$curScrotName" "$curScrot"
+            fi
+        else
+            menuItem "Install $curScrotName" "$0 --$curScrot"
+        fi
+    done
+    menuEnd
 fi
 exit 0
diff --git a/bl-multimedia-pipemenu b/bl-multimedia-pipemenu
--- a/bl-multimedia-pipemenu
+++ b/bl-multimedia-pipemenu
@@ -7,8 +7,8 @@
 #
 # Modified by <damo> for BunsenLabs Linux   April 2015
 #
-# 	To change the entries shown in the Multimedia pipemenu:
-# 	edit ".config/openbox/pipemenus.rc"
+#   To change the entries shown in the Multimedia pipemenu:
+#   edit ".config/openbox/pipemenus.rc"
 #
 # ---------------------------------------------------------------------
 
@@ -22,85 +22,85 @@ source $USR_CFG
 # create a function called setupappName, it will be called automatically.
 
 if ! . "$BL_COMMON_LIBDIR/bl-include.cfg" 2> /dev/null; then
-	echo $"Error: Failed to locate bl-include.cfg in $BL_COMMON_LIBDIR" >&2
-	exit 1
+    echo $"Error: Failed to locate bl-include.cfg in $BL_COMMON_LIBDIR" >&2
+    exit 1
 elif ! . "$USR_CFG" 2> /dev/null; then
-	echo $"Error: Failed to locate pipemenu.rc in $USR_CFG" >&2
-	exit 1
+    echo $"Error: Failed to locate pipemenu.rc in $USR_CFG" >&2
+    exit 1
 fi
 
 appExists() {
-	for curApp in "${MM_APPS[@]}"; do # if $packageName exists in MM_APPS array
-		[[ $curApp = "$1" ]] &&
-			return 0
-	done
-	say "Unable to install $1. There is no such application that I know of." 1 >&2
-	say "You can try one of these: ${MM_APPS[*]}" 2 >&2
-	return 1
+    for curApp in "${MM_APPS[@]}"; do # if $packageName exists in MM_APPS array
+        [[ $curApp = "$1" ]] &&
+            return 0
+    done
+    say "Unable to install $1. There is no such application that I know of." 1 >&2
+    say "You can try one of these: ${MM_APPS[*]}" 2 >&2
+    return 1
 }
 
 if [[ $1 && ! $1 = --install-* ]]; then
-	packageName=${1#--}
-	read -ra words <<< "${packageName//-/ }"
-	x-terminal-emulator -T "Install ${words[*]^}" -e "$0" "--install-$packageName"
+    packageName=${1#--}
+    read -ra words <<< "${packageName//-/ }"
+    x-terminal-emulator -T "Install ${words[*]^}" -e "$0" "--install-$packageName"
 
 elif [[ $1 = --install-* ]]; then
-	packageName=${1#--install-}
-	appExists "$packageName" || exit 1
-	appName=${packageName//-/ }
-	read -ra words <<< "$appName"
-	appName=${words[*]^}
-	appNameUpper=${appName^^}
+    packageName=${1#--install-}
+    appExists "$packageName" || exit 1
+    appName=${packageName//-/ }
+    read -ra words <<< "$appName"
+    appName=${words[*]^}
+    appNameUpper=${appName^^}
 
-	setupFunctionName="setup${appName//[^a-zA-Z]/}" # setupFunctionName should now be in format like 'setupBlender'
-	if [[ $(type -t "$setupFunctionName") = 'function' ]]; then
-		promptInstall --setup "$setupFunctionName" "${appNameUpper% APP} APP" "$appName" "$packageName"
-	else
-		promptInstall "${appNameUpper% APP} APP" "$appName" "$packageName"
-	fi
+    setupFunctionName="setup${appName//[^a-zA-Z]/}" # setupFunctionName should now be in format like 'setupBlender'
+    if [[ $(type -t "$setupFunctionName") = 'function' ]]; then
+        promptInstall --setup "$setupFunctionName" "${appNameUpper% APP} APP" "$appName" "$packageName"
+    else
+        promptInstall "${appNameUpper% APP} APP" "$appName" "$packageName"
+    fi
 
 else # pipemenu
-	menuStart
-	for curApp in "${MM_APPS[@]}"; do
-		read -ra words <<< "${curApp//-/ }"
-		echo "$curApp"
-		curAppName=${words[*]^}
-		if type "$curApp" &> /dev/null; then
-			# change name of smplayer (gui frontend for mplayer)
-			if [[ "$curApp" = "smplayer" ]];then
-				menuItem "Gnome mplayer" "$curApp"
-				curAppName=${words[*]^}
-			elif [[ "$curApp" = "mpv" ]];then # set mpv to start with gui window
-				menuItem "$curAppName" "$curApp --force-window --idle"
-			else
-				menuItem "$curAppName" "$curApp"
-			fi
-		else
-			if [[ "$curAppName" == "Smplayer" ]]; then
-				menuItem "Install Gnome mplayer" "$0 --$curApp"
-			else
-				menuItem "Install $curAppName" "$0 --$curApp"
-			fi
-		fi
-	done
+    menuStart
+    for curApp in "${MM_APPS[@]}"; do
+        read -ra words <<< "${curApp//-/ }"
+        echo "$curApp"
+        curAppName=${words[*]^}
+        if type "$curApp" &> /dev/null; then
+            # change name of smplayer (gui frontend for mplayer)
+            if [[ "$curApp" = "smplayer" ]];then
+                menuItem "Gnome mplayer" "$curApp"
+                curAppName=${words[*]^}
+            elif [[ "$curApp" = "mpv" ]];then # set mpv to start with gui window
+                menuItem "$curAppName" "$curApp --force-window --idle"
+            else
+                menuItem "$curAppName" "$curApp"
+            fi
+        else
+            if [[ "$curAppName" == "Smplayer" ]]; then
+                menuItem "Install Gnome mplayer" "$0 --$curApp"
+            else
+                menuItem "Install $curAppName" "$0 --$curApp"
+            fi
+        fi
+    done
     menuSeparator
-	menuSeparator 'Editors'
+    menuSeparator 'Editors'
     # get editors pipemenu
-	if ! type "bl-mmeditors-pipemenu" &> /dev/null; then
-		echo $"Error: Failed to locate bl-mmeditors-pipemenu in $BL_INCLUDE" >&2
-		exit 1
-	else
-		echo $(bl-mmeditors-pipemenu)
-	fi
+    if ! type "bl-mmeditors-pipemenu" &> /dev/null; then
+        echo $"Error: Failed to locate bl-mmeditors-pipemenu in $BL_INCLUDE" >&2
+        exit 1
+    else
+        echo $(bl-mmeditors-pipemenu)
+    fi
     menuSeparator
-	menuSeparator 'Utilities'
+    menuSeparator 'Utilities'
     # get utilities pipemenu
-	if ! type "bl-mmutils-pipemenu" &> /dev/null; then
-		echo $"Error: Failed to locate bl-mmutils-pipemenu in $BL_INCLUDE" >&2
-		exit 1
-	else
-		echo $(bl-mmutils-pipemenu)
-	fi
-	menuEnd
+    if ! type "bl-mmutils-pipemenu" &> /dev/null; then
+        echo $"Error: Failed to locate bl-mmutils-pipemenu in $BL_INCLUDE" >&2
+        exit 1
+    else
+        echo $(bl-mmutils-pipemenu)
+    fi
+    menuEnd
 fi
 exit 0
