Add source for arrays

diff --git a/bl-graphics-pipemenu b/bl-graphics-pipemenu
--- a/bl-graphics-pipemenu
+++ b/bl-graphics-pipemenu
@@ -5,14 +5,17 @@
 # Originally written for CrunchBang Linux <http://crunchbang.org/>
 # by Philip Newborough (aka corenominal) <mail@philipnewborough.co.uk>
 #
-# Modified by damo for BunsenLabs Linux
+# Modified by <damo> for BunsenLabs Linux   April 2015
+#
+# 	To change the entries shown in the Graphics pipemenu:
+# 	edit ".config/openbox/menu-graphics.cfg"
+#
 # ---------------------------------------------------------------------
 
 BL_COMMON_LIBDIR='/usr/lib/bunsen/bunsen-common'
+USR_CFG='.config/openbox/menu-graphics.cfg'
 
-# In order to add another APP, add the package name to this array:
-TOOLS=( 'mirage' 'gimp' 'blender' 'inkscape' 'mandelbulber' 'viewnior')
-SCROTS=('xfce4-screenshooter' 'scrot')
+source $USR_CFG
 
 # Get $USER images directory
 #if test -f "/usr/bin/xdg-user-dir";then
@@ -31,13 +34,16 @@ fi
 # If the package needs additional configuration before installation
 # create a function called setupappName, it will be called automatically.
 
-
 if ! . "$BL_COMMON_LIBDIR/bl-include.cfg" 2> /dev/null; then
 	echo $"Error: Failed to locate bl-include.cfg in $BL_COMMON_LIBDIR" >&2
+	exit 1
+elif ! . "$USR_CFG" 2> /dev/null; then
+	echo $"Error: Failed to locate menu-graphics.cfg in $BL_COMMON_LIBDIR" >&2
 	exit 1
 fi
 
 appExists() {
+
 	for curTool in "${TOOLS[@]}"; do # if $packageName exists in tools array
 		[[ $curTool = "$1" ]] &&
 			return 0
diff --git a/bl-mmeditors-pipemenu b/bl-mmeditors-pipemenu
--- a/bl-mmeditors-pipemenu
+++ b/bl-mmeditors-pipemenu
@@ -6,13 +6,13 @@
 # Originally written for CrunchBang Linux <http://crunchbang.org/>
 # by Philip Newborough (aka corenominal) <mail@philipnewborough.co.uk>
 #
-# Modified by <damo> for BunsenLabs Linux, March 2015
+# Modified by <damo> for BunsenLabs Linux, April 2015
 # ---------------------------------------------------------------------
 
 BL_COMMON_LIBDIR='/usr/lib/bunsen/bunsen-common'
+USR_CFG='.config/openbox/menu-multimedia.cfg'
 
-# In order to add another TOOL, add the package name to this array:
-TOOLS=('mhwaveedit' 'audacity' 'openshot')
+source $USR_CFG
 
 # If the package needs additional configuration before installation
 # create a function called setuptoolName, it will be called automatically.
@@ -20,6 +20,9 @@ TOOLS=('mhwaveedit' 'audacity' 'openshot')
 
 if ! . "$BL_COMMON_LIBDIR/bl-include.cfg" 2> /dev/null; then
 	echo $"Error: Failed to locate bl-include.cfg in $BL_COMMON_LIBDIR" >&2
+	exit 1
+elif ! . "$USR_CFG" 2> /dev/null; then
+	echo $"Error: Failed to locate menu-multimedia.cfg in $BL_COMMON_LIBDIR" >&2
 	exit 1
 fi
 
diff --git a/bl-multimedia-pipemenu b/bl-multimedia-pipemenu
--- a/bl-multimedia-pipemenu
+++ b/bl-multimedia-pipemenu
@@ -7,15 +7,16 @@
 #
 # Modified by <damo> for BunsenLabs Linux, March 2015
 # ---------------------------------------------------------------------
-# Applications to display in the editors and utilities sections can be
-# changed by editing the "TOOLS" arrays in:
-#           $BL_INCLUDE/bl-mmeditors-pipemenu
-#           $BL_INCLUDE/bl-mmutils-pipemenu
+#	To change the entries shown in the Multimedia pipemenu
+#	edit ".config/openbox/menu-graphics.cfg"
 # ---------------------------------------------------------------------
 
 
 BL_COMMON_LIBDIR='/usr/lib/bunsen/bunsen-common'
 BL_INCLUDE='/usr/bin'   # used for editor and utility pipemenus
+USR_CFG='.config/openbox/menu-multimedia.cfg'
+
+source $USR_CFG
 
 # In order to add another APP, add the package name to this array:
 APPS=( 'vlc' 'mpv' 'audacious' 'smplayer' )
@@ -26,6 +27,9 @@ APPS=( 'vlc' 'mpv' 'audacious' 'smplayer' )
 
 if ! . "$BL_COMMON_LIBDIR/bl-include.cfg" 2> /dev/null; then
 	echo $"Error: Failed to locate bl-include.cfg in $BL_COMMON_LIBDIR" >&2
+	exit 1
+elif ! . "$USR_CFG" 2> /dev/null; then
+	echo $"Error: Failed to locate menu-multimedia.cfg in $BL_COMMON_LIBDIR" >&2
 	exit 1
 fi
 
diff --git a/bl-x-www-browser-pipemenu b/bl-x-www-browser-pipemenu
--- a/bl-x-www-browser-pipemenu
+++ b/bl-x-www-browser-pipemenu
@@ -4,11 +4,15 @@
 # Originally written for CrunchBang Linux <http://crunchbang.org/>
 # by Philip Newborough (aka corenominal) <corenominal@corenominal.org>
 # ---------------------------------------------------------------------
+#	To change the entries shown in the Browsers pipemenu
+#	edit ".config/openbox/menu-browsers.cfg"
+#----------------------------------------------------------------------
 
 BL_COMMON_LIBDIR='/usr/lib/bunsen/bunsen-common'
+USR_CFG='.config/openbox/menu-browsers.cfg'
 
-# In order to add another browser, add the package name to this array:
-TOOLS=('chromium' 'iceweasel' 'google-chrome-stable' 'opera')
+source $USR_CFG
+
 # If the package needs additional configuration before installation
 # create a function called setupBrowserName, it will be called automatically.
 
@@ -18,6 +22,9 @@ KEY_URLS_OPERA=('http://deb.opera.com/archive.key' 'http://packages.crunchbang.o
 if ! . "$BL_COMMON_LIBDIR/bl-include.cfg" 2> /dev/null; then
     echo $"Error: Failed to locate bl-include.cfg in $BL_COMMON_LIBDIR" >&2
     exit 1
+elif ! . "$USR_CFG" 2> /dev/null; then
+	echo $"Error: Failed to locate menu-multimedia.cfg in $BL_COMMON_LIBDIR" >&2
+	exit 1
 fi
 
 browserExists() {
@@ -80,10 +87,12 @@ elif [[ $1 = --install-* ]]; then
 
     setupFunctionName="setup${browserName//[^a-zA-Z]/}" # setupFunctionName should now be in format like 'setupChromium'
     if [[ $(type -t "$setupFunctionName") = 'function' ]]; then
-        promptInstall --setup "$setupFunctionName" "${browserNameUpper% BROWSER} BROWSER" "$browserName" "$packageName"
+        export setupFunctionName
     else
-        promptInstall "${browserNameUpper% BROWSER} BROWSER" "$browserName" "$packageName"
+        unset setupFunctionName
     fi
+
+    promptInstall "${browserNameUpper% BROWSER} BROWSER" "$browserName" "$packageName"
 
 else # pipemenu
     INSTALLED=false
@@ -94,7 +103,7 @@ else # pipemenu
         if type "$curTool" &> /dev/null; then
             INSTALLED=true
             menuItem "$curToolName" "$curTool"
-            [[ $curTool = 'chromium' || $curTool = google-chrome-* ]] &&
+            [[ $curTool = chrom* ]] &&
                 menuItem "$curToolName (Private Mode)" "$curTool --incognito" # Incognito mode for chrome and chromium
         else
             menuItem "Install $curToolName" "$0 --$curTool"
