Change to USR_CFG_DIR; make source tests consistent

diff --git a/bl-graphics-pipemenu b/bl-graphics-pipemenu
--- a/bl-graphics-pipemenu
+++ b/bl-graphics-pipemenu
@@ -13,13 +13,9 @@
 # ---------------------------------------------------------------------
 
 BL_COMMON_LIBDIR='/usr/lib/bunsen/bunsen-common'
-USR_CFG='.config/openbox/pipemenus.rc'
-
-#source $USR_CFG
+USR_CFG_DIR="$HOME/.config/openbox"
 
 # Get $USER images directory
-#if test -f "/usr/bin/xdg-user-dir";then
-
 if type xdg-user-dir &>/dev/null; then
     IMGDIR=$(xdg-user-dir PICTURES)
 else
@@ -37,8 +33,8 @@ fi
 if ! . "$BL_COMMON_LIBDIR/bl-include.cfg" 2> /dev/null; then
     echo $"Error: Failed to locate bl-include.cfg in $BL_COMMON_LIBDIR" >&2
     exit 1
-elif ! . "$USR_CFG" 2> /dev/null; then
-    echo $"Error: Failed to locate pipemenus.rc in $USR_CFG" >&2
+elif ! . "$USR_CFG_DIR/pipemenus.rc" 2> /dev/null; then
+    echo $"Error: Failed to locate pipemenus.rc in $USR_CFG_DIR" >&2
     exit 1
 fi
 
diff --git a/bl-kb-pipemenu b/bl-kb-pipemenu
--- a/bl-kb-pipemenu
+++ b/bl-kb-pipemenu
@@ -10,9 +10,10 @@
 # commands, which just exit the menu
 #-----------------------------------------------------------------------
 BL_COMMON_LIBDIR="/usr/lib/bunsen/bunsen-common"
+USR_CFG_DIR="$HOME/.config/openbox"
 KBSCRIPT="bl-kb.py"
-RCPATH=".config/openbox/rc.xml"
-KBTEXT=".config/openbox/kbinds.txt"
+RCPATH="$USR_CFG_DIR/rc.xml"
+KBTEXT="$USR_CFG_DIR/kbinds.txt"
 
 if ! . "$BL_COMMON_LIBDIR/bl-include.cfg" 2> /dev/null; then
     echo $"Error: Failed to locate bl-include.cfg in $BL_COMMON_LIBDIR" >&2
@@ -25,7 +26,7 @@ if ! [ -e "$KBTEXT" ];then # write keybinds to textfile, if it doesn't exist
         # run script to write kbinds.txt, suppress terminal output
         "$KBSCRIPT" > /dev/null
     else
-        echo $"ERROR: bl-kb.py not found" >&2
+        echo $"ERROR: $KBSCRIPT not found" >&2
         exit 1
     fi
 fi
@@ -41,8 +42,8 @@ fi
 
 # pipemenu
 menuStart
-menuItem "Backup and Edit rc.xml" "bl-kb-pipemenu --rcedit"
-menuItem "Refesh keybinds list" "bl-kb.py" # use if rc.xml has been edited
+menuItem "Backup and Edit rc.xml" "$@ --rcedit"
+menuItem "Refesh keybinds list" "$KBSCRIPT" # use if rc.xml has been edited
 menuSeparator
 menuSeparator "Openbox window commands"
 while read -r a b c;do      # write out Openbox commands (not clickable)
diff --git a/bl-mmeditors-pipemenu b/bl-mmeditors-pipemenu
--- a/bl-mmeditors-pipemenu
+++ b/bl-mmeditors-pipemenu
@@ -10,9 +10,7 @@
 # ---------------------------------------------------------------------
 
 BL_COMMON_LIBDIR='/usr/lib/bunsen/bunsen-common'
-USR_CFG='.config/openbox/pipemenus.rc'
-
-source $USR_CFG
+USR_CFG_DIR="$HOME/.config/openbox"
 
 # If the package needs additional configuration before installation
 # create a function called setuptoolName, it will be called automatically.
@@ -20,8 +18,8 @@ source $USR_CFG
 if ! . "$BL_COMMON_LIBDIR/bl-include.cfg" 2> /dev/null; then
     echo $"Error: Failed to locate bl-include.cfg in $BL_COMMON_LIBDIR" >&2
     exit 1
-elif ! . "$USR_CFG" 2> /dev/null; then
-    echo $"Error: Failed to locate pipemenus.rc in $USR_CFG" >&2
+elif ! . "$USR_CFG_DIR/pipemenus.rc" 2> /dev/null; then
+    echo $"Error: Failed to locate pipemenus.rc in $USR_CFG_DIR" >&2
     exit 1
 fi
 
diff --git a/bl-mmutils-pipemenu b/bl-mmutils-pipemenu
--- a/bl-mmutils-pipemenu
+++ b/bl-mmutils-pipemenu
@@ -10,61 +10,59 @@
 # ---------------------------------------------------------------------
 
 BL_COMMON_LIBDIR='/usr/lib/bunsen/bunsen-common'
-USR_CFG='.config/openbox/pipemenus.rc'
-
-source $USR_CFG
+USR_CFG_DIR="$HOME/.config/openbox"
 
 # If the package needs additional configuration before installation
 # create a function called setuptoolName, it will be called automatically.
 
 if ! . "$BL_COMMON_LIBDIR/bl-include.cfg" 2> /dev/null; then
-	echo $"Error: Failed to locate bl-include.cfg in $BL_COMMON_LIBDIR" >&2
-	exit 1
-elif ! . "$USR_CFG" 2> /dev/null; then
-	echo $"Error: Failed to locate pipemenus.rc in $USR_CFG" >&2
-	exit 1
+    echo $"Error: Failed to locate bl-include.cfg in $BL_COMMON_LIBDIR" >&2
+    exit 1
+elif ! . "$USR_CFG_DIR/pipemenus.rc" 2> /dev/null; then
+    echo $"Error: Failed to locate pipemenus.rc in $USR_CFG_DIR" >&2
+    exit 1
 fi
 
 utilExists() {
-	for curUtil in "${MM_UTILS[@]}"; do # if $packageName exists in TOOLS array
-		[[ $curUtil = "$1" ]] &&
-			return 0
-	done
-	say "Unable to install $1. There is no such application that I know of." 1 >&2
-	say "You can try one of these: ${MM_UTILS[*]}" 2 >&2
-	return 1
+    for curUtil in "${MM_UTILS[@]}"; do # if $packageName exists in TOOLS array
+        [[ $curUtil = "$1" ]] &&
+            return 0
+    done
+    say "Unable to install $1. There is no such application that I know of." 1 >&2
+    say "You can try one of these: ${MM_UTILS[*]}" 2 >&2
+    return 1
 }
 
 if [[ $1 && ! $1 = --install-* ]]; then
-	packageName=${1#--}
-	read -ra words <<< "${packageName//-/ }"
-	x-terminal-emulator -T "Install ${words[*]^}" -e "$0" "--install-$packageName"
+    packageName=${1#--}
+    read -ra words <<< "${packageName//-/ }"
+    x-terminal-emulator -T "Install ${words[*]^}" -e "$0" "--install-$packageName"
 
 elif [[ $1 = --install-* ]]; then
-	packageName=${1#--install-}
-	utilExists "$packageName" || exit 1
-	toolName=${packageName//-/ }
-	read -ra words <<< "$toolName"
-	toolName=${words[*]^}
-	toolNameUpper=${toolName^^}
+    packageName=${1#--install-}
+    utilExists "$packageName" || exit 1
+    toolName=${packageName//-/ }
+    read -ra words <<< "$toolName"
+    toolName=${words[*]^}
+    toolNameUpper=${toolName^^}
 
-	setupFunctionName="setup${toolName//[^a-zA-Z]/}" # setupFunctionName should now be in format like 'setupBlender'
-	if [[ $(type -t "$setupFunctionName") = 'function' ]]; then
-		promptInstall --setup "$setupFunctionName" "${toolNameUpper% TOOL} TOOL" "$toolName" "$packageName"
-	else
-		promptInstall "${toolNameUpper% TOOL} TOOL" "$toolName" "$packageName"
-	fi
+    setupFunctionName="setup${toolName//[^a-zA-Z]/}" # setupFunctionName should now be in format like 'setupBlender'
+    if [[ $(type -t "$setupFunctionName") = 'function' ]]; then
+        promptInstall --setup "$setupFunctionName" "${toolNameUpper% TOOL} TOOL" "$toolName" "$packageName"
+    else
+        promptInstall "${toolNameUpper% TOOL} TOOL" "$toolName" "$packageName"
+    fi
 
 else # output for bl-multimedia-pipemenu
-	for curUtil in "${MM_UTILS[@]}"; do
-		read -ra words <<< "${curUtil//-/ }"
-		curUtilName=${words[*]^}
-		if type "$curUtil" &> /dev/null; then
-			menuItem "$curUtilName" "$curUtil"
-		else
-			menuItem "Install $curUtilName" "$0 --$curUtil"
-		fi
-	done
+    for curUtil in "${MM_UTILS[@]}"; do
+        read -ra words <<< "${curUtil//-/ }"
+        curUtilName=${words[*]^}
+        if type "$curUtil" &> /dev/null; then
+            menuItem "$curUtilName" "$curUtil"
+        else
+            menuItem "Install $curUtilName" "$0 --$curUtil"
+        fi
+    done
 
 fi
 exit 0
diff --git a/bl-multimedia-pipemenu b/bl-multimedia-pipemenu
--- a/bl-multimedia-pipemenu
+++ b/bl-multimedia-pipemenu
@@ -13,10 +13,7 @@
 # ---------------------------------------------------------------------
 
 BL_COMMON_LIBDIR='/usr/lib/bunsen/bunsen-common'
-BL_INCLUDE='/usr/bin'   # used for editor and utility pipemenus
-USR_CFG='.config/openbox/pipemenus.rc'
-
-source $USR_CFG
+USR_CFG_DIR="$HOME/.config/openbox"
 
 # If the package needs additional configuration before installation
 # create a function called setupappName, it will be called automatically.
@@ -24,8 +21,8 @@ source $USR_CFG
 if ! . "$BL_COMMON_LIBDIR/bl-include.cfg" 2> /dev/null; then
     echo $"Error: Failed to locate bl-include.cfg in $BL_COMMON_LIBDIR" >&2
     exit 1
-elif ! . "$USR_CFG" 2> /dev/null; then
-    echo $"Error: Failed to locate pipemenu.rc in $USR_CFG" >&2
+elif ! . "$USR_CFG_DIR/pipemenus.rc" 2> /dev/null; then
+    echo $"Error: Failed to locate pipemenus.rc in $USR_CFG_DIR" >&2
     exit 1
 fi
 
@@ -87,7 +84,7 @@ else # pipemenu
     menuSeparator 'Editors'
     # get editors pipemenu
     if ! type "bl-mmeditors-pipemenu" &> /dev/null; then
-        echo $"Error: Failed to locate bl-mmeditors-pipemenu in $BL_INCLUDE" >&2
+        echo $"Error: Failed to locate bl-mmeditors-pipemenu" >&2
         exit 1
     else
         echo $(bl-mmeditors-pipemenu)
@@ -96,7 +93,7 @@ else # pipemenu
     menuSeparator 'Utilities'
     # get utilities pipemenu
     if ! type "bl-mmutils-pipemenu" &> /dev/null; then
-        echo $"Error: Failed to locate bl-mmutils-pipemenu in $BL_INCLUDE" >&2
+        echo $"Error: Failed to locate bl-mmutils-pipemenu" >&2
         exit 1
     else
         echo $(bl-mmutils-pipemenu)
