Application arrays now read from pipemenus.rc

diff --git a/bl-graphics-pipemenu b/bl-graphics-pipemenu
--- a/bl-graphics-pipemenu
+++ b/bl-graphics-pipemenu
@@ -13,7 +13,7 @@
 # ---------------------------------------------------------------------
 
 BL_COMMON_LIBDIR='/usr/lib/bunsen/bunsen-common'
-USR_CFG='.config/openbox/menu-graphics.cfg'
+USR_CFG='.config/openbox/pipemenus.rc'
 
 source $USR_CFG
 
@@ -38,28 +38,28 @@ if ! . "$BL_COMMON_LIBDIR/bl-include.cfg" 2> /dev/null; then
 	echo $"Error: Failed to locate bl-include.cfg in $BL_COMMON_LIBDIR" >&2
 	exit 1
 elif ! . "$USR_CFG" 2> /dev/null; then
-	echo $"Error: Failed to locate menu-graphics.cfg in $BL_COMMON_LIBDIR" >&2
+	echo $"Error: Failed to locate pipemenus.rc in $USR_CFG" >&2
 	exit 1
 fi
 
 appExists() {
 
-	for curTool in "${TOOLS[@]}"; do # if $packageName exists in tools array
-		[[ $curTool = "$1" ]] &&
+	for curApp in "${GRAPHICS_APPS[@]}"; do # if $packageName exists in tools array
+		[[ $curApp = "$1" ]] &&
 			return 0
 	done
 	say "Unable to install $1. There is no such application that I know of." 1 >&2
-	say "You can try one of these: ${TOOLS[*]}" 2 >&2
+	say "You can try one of these: ${GRAPHICS_APPS[*]}" 2 >&2
 	return 1
 }
 
 screenshooterExists() {
-	for curScrot in "${SCROTS[@]}"; do # if $packageName exists in scrots array
+	for curScrot in "${GRAPHICS_SCROTS[@]}"; do # if $packageName exists in scrots array
 		[[ $curScrot = "$1" ]] &&
 			return 0
 	done
 	say "Unable to install $1. There is no such application that I know of." 1 >&2
-	say "You can try one of these: ${SCROTS[*]}" 2 >&2
+	say "You can try one of these: ${GRAPHICS_SCROTS[*]}" 2 >&2
 	return 1
 }
 
@@ -102,18 +102,18 @@ elif [[ $1 = --install-* ]]; then
 
 else # pipemenu
 	menuStart
-	for curTool in "${TOOLS[@]}"; do
-		read -ra words <<< "${curTool//-/ }"
-		curToolName=${words[*]^}
-		if type "$curTool" &> /dev/null; then
-			menuItem "$curToolName" "$curTool"
+	for curApp in "${GRAPHICS_APPS[@]}"; do
+		read -ra words <<< "${curApp//-/ }"
+		curAppName=${words[*]^}
+		if type "$curApp" &> /dev/null; then
+			menuItem "$curAppName" "$curApp"
 		else
-			menuItem "Install $curToolName" "$0 --$curTool"
+			menuItem "Install $curAppName" "$0 --$curApp"
 		fi
 	done
 	menuSeparator 'Screenshots'
 
-	for curScrot in "${SCROTS[@]}"; do
+	for curScrot in "${GRAPHICS_SCROTS[@]}"; do
 		read -ra words <<< "${curScrot//-/ }"
 		curScrotName=${words[*]^}
 		if type "$curScrot" &> /dev/null; then
diff --git a/bl-mmeditors-pipemenu b/bl-mmeditors-pipemenu
--- a/bl-mmeditors-pipemenu
+++ b/bl-mmeditors-pipemenu
@@ -10,32 +10,30 @@
 # ---------------------------------------------------------------------
 
 BL_COMMON_LIBDIR='/usr/lib/bunsen/bunsen-common'
-USR_CFG='.config/openbox/menu-multimedia.cfg'
+USR_CFG='.config/openbox/pipemenus.rc'
 
 source $USR_CFG
 
 # If the package needs additional configuration before installation
 # create a function called setuptoolName, it will be called automatically.
 
-
 if ! . "$BL_COMMON_LIBDIR/bl-include.cfg" 2> /dev/null; then
 	echo $"Error: Failed to locate bl-include.cfg in $BL_COMMON_LIBDIR" >&2
 	exit 1
 elif ! . "$USR_CFG" 2> /dev/null; then
-	echo $"Error: Failed to locate menu-multimedia.cfg in $BL_COMMON_LIBDIR" >&2
+	echo $"Error: Failed to locate pipemenus.rc in $USR_CFG" >&2
 	exit 1
 fi
 
 toolExists() {
-	for curTool in "${TOOLS[@]}"; do # if $packageName exists in TOOLS array
+	for curTool in "${MM_EDITORS[@]}"; do # if $packageName exists in TOOLS array
 		[[ $curTool = "$1" ]] &&
 			return 0
 	done
 	say "Unable to install $1. There is no such application that I know of." 1 >&2
-	say "You can try one of these: ${TOOLS[*]}" 2 >&2
+	say "You can try one of these: ${MM_EDITORS[*]}" 2 >&2
 	return 1
 }
-
 
 if [[ $1 && ! $1 = --install-* ]]; then
 	packageName=${1#--}
@@ -58,7 +56,7 @@ elif [[ $1 = --install-* ]]; then
 	fi
 
 else # output for bl-multimedia-pipemenu
-	for curTool in "${TOOLS[@]}"; do
+	for curTool in "${MM_EDITORS[@]}"; do
 		read -ra words <<< "${curTool//-/ }"
 		curToolName=${words[*]^}
 		if type "$curTool" &> /dev/null; then
diff --git a/bl-mmutils-pipemenu b/bl-mmutils-pipemenu
--- a/bl-mmutils-pipemenu
+++ b/bl-mmutils-pipemenu
@@ -1,7 +1,7 @@
 #!/bin/bash
 # ---------------------------------------------------------------------
-# An Openbox pipemenu for Multimedia utilities
-# It is used by bl-multimedia-pipemenu to populate the MM utils menu
+# An Openbox pipemenu for Multimedia editors
+# It is used by bl-multimedia-pipemenu to populate the MM editors menu
 #
 # Originally written for CrunchBang Linux <http://crunchbang.org/>
 # by Philip Newborough (aka corenominal) <mail@philipnewborough.co.uk>
@@ -10,32 +10,30 @@
 # ---------------------------------------------------------------------
 
 BL_COMMON_LIBDIR='/usr/lib/bunsen/bunsen-common'
-USR_CFG='.config/openbox/menu-multimedia.cfg'
+USR_CFG='.config/openbox/pipemenus.rc'
 
 source $USR_CFG
 
 # If the package needs additional configuration before installation
-# create a function called setuputilName, it will be called automatically.
-
+# create a function called setuptoolName, it will be called automatically.
 
 if ! . "$BL_COMMON_LIBDIR/bl-include.cfg" 2> /dev/null; then
 	echo $"Error: Failed to locate bl-include.cfg in $BL_COMMON_LIBDIR" >&2
 	exit 1
 elif ! . "$USR_CFG" 2> /dev/null; then
-	echo $"Error: Failed to locate menu-multimedia.cfg in $BL_COMMON_LIBDIR" >&2
+	echo $"Error: Failed to locate pipemenus.rc in $USR_CFG" >&2
 	exit 1
 fi
 
-utilExists() {
-	for curUtil in "${UTILS[@]}"; do # if $packageName exists in UTILS array
-		[[ $curUtil = "$1" ]] &&
+toolExists() {
+	for curTool in "${MM_EDITORS[@]}"; do # if $packageName exists in TOOLS array
+		[[ $curTool = "$1" ]] &&
 			return 0
 	done
 	say "Unable to install $1. There is no such application that I know of." 1 >&2
-	say "You can try one of these: ${UTILS[*]}" 2 >&2
+	say "You can try one of these: ${MM_EDITORS[*]}" 2 >&2
 	return 1
 }
-
 
 if [[ $1 && ! $1 = --install-* ]]; then
 	packageName=${1#--}
@@ -44,32 +42,27 @@ if [[ $1 && ! $1 = --install-* ]]; then
 
 elif [[ $1 = --install-* ]]; then
 	packageName=${1#--install-}
-	utilExists "$packageName" || exit 1
-	utilName=${packageName//-/ }
-	read -ra words <<< "$utilName"
-	utilName=${words[*]^}
-	utilNameUpper=${utilName^^}
+	toolExists "$packageName" || exit 1
+	toolName=${packageName//-/ }
+	read -ra words <<< "$toolName"
+	toolName=${words[*]^}
+	toolNameUpper=${toolName^^}
 
-	setupFunctionName="setup${utilName//[^a-zA-Z]/}" # setupFunctionName should now be in format like 'setupBlender'
+	setupFunctionName="setup${toolName//[^a-zA-Z]/}" # setupFunctionName should now be in format like 'setupBlender'
 	if [[ $(type -t "$setupFunctionName") = 'function' ]]; then
-		promptInstall --setup "$setupFunctionName" "${utilNameUpper% UTIL} UTIL" "$utilName" "$packageName"
+		promptInstall --setup "$setupFunctionName" "${toolNameUpper% TOOL} TOOL" "$toolName" "$packageName"
 	else
-		promptInstall "${utilNameUpper% UTIL} UTIL" "$utilName" "$packageName"
+		promptInstall "${toolNameUpper% TOOL} TOOL" "$toolName" "$packageName"
 	fi
 
 else # output for bl-multimedia-pipemenu
-	for curUtil in "${UTILS[@]}"; do
-		read -ra words <<< "${curUtil//-/ }"
-		curUtilName=${words[*]^}
-		if type "$curUtil" &> /dev/null; then
-		# change volti to volti-mixer
-			if [[ "$curUtil" = "volti" ]];then
-				menuItem "$curUtilName volume control" "$curUtil-mixer"
-			else
-				menuItem "$curUtilName" "$curUtil"
-			fi
+	for curTool in "${MM_EDITORS[@]}"; do
+		read -ra words <<< "${curTool//-/ }"
+		curToolName=${words[*]^}
+		if type "$curTool" &> /dev/null; then
+			menuItem "$curToolName" "$curTool"
 		else
-			menuItem "Install $curUtilName" "$0 --$curUtil"
+			menuItem "Install $curToolName" "$0 --$curTool"
 		fi
 	done
 
diff --git a/bl-x-www-browser-pipemenu b/bl-x-www-browser-pipemenu
--- a/bl-x-www-browser-pipemenu
+++ b/bl-x-www-browser-pipemenu
@@ -9,7 +9,7 @@
 #----------------------------------------------------------------------
 
 BL_COMMON_LIBDIR='/usr/lib/bunsen/bunsen-common'
-USR_CFG='.config/openbox/menu-browsers.cfg'
+USR_CFG='.config/openbox/pipemenus.rc'
 
 source $USR_CFG
 
@@ -23,17 +23,17 @@ if ! . "$BL_COMMON_LIBDIR/bl-include.cfg" 2> /dev/null; then
     echo $"Error: Failed to locate bl-include.cfg in $BL_COMMON_LIBDIR" >&2
     exit 1
 elif ! . "$USR_CFG" 2> /dev/null; then
-	echo $"Error: Failed to locate menu-multimedia.cfg in $BL_COMMON_LIBDIR" >&2
+	echo $"Error: Failed to locate pipemenus.rc in $USR_CFG" >&2
 	exit 1
 fi
 
 browserExists() {
-    for curTool in "${TOOLS[@]}"; do # if $packageName exists in tools array
-        [[ $curTool = "$1" ]] &&
+    for curBrowser in "${BROWSERS[@]}"; do # if $packageName exists in BROWSERS array
+        [[ $curBrowser = "$1" ]] &&
             return 0
     done
     say "Unable to install $1. There is no such browser that I know of." 1 >&2
-    say "You can try one of these: ${TOOLS[*]}" 2 >&2
+    say "You can try one of these: ${BROWSERS[*]}" 2 >&2
     return 1
 }
 
@@ -97,16 +97,16 @@ elif [[ $1 = --install-* ]]; then
 else # pipemenu
     INSTALLED=false
     menuStart
-    for curTool in "${TOOLS[@]}"; do
-        read -ra words <<< "${curTool//-/ }"
-        curToolName=${words[*]^}
-        if type "$curTool" &> /dev/null; then
+    for curBrowser in "${BROWSERS[@]}"; do
+        read -ra words <<< "${curBrowser//-/ }"
+        curBrowserName=${words[*]^}
+        if type "$curBrowser" &> /dev/null; then
             INSTALLED=true
-            menuItem "$curToolName" "$curTool"
-            [[ $curTool = chrom* ]] &&
-                menuItem "$curToolName (Private Mode)" "$curTool --incognito" # Incognito mode for chrome and chromium
+            menuItem "$curBrowserName" "$curBrowser"
+            [[ $curBrowser = chrom* ]] &&
+                menuItem "$curBrowserName (Private Mode)" "$curBrowser --incognito" # Incognito mode for chrome and chromium
         else
-            menuItem "Install $curToolName" "$0 --$curTool"
+            menuItem "Install $curBrowserName" "$0 --$curBrowser"
         fi
     done
 
