Changed so editors and utils are called from media1- and media2- pipemenus

diff --git a/bl-multimedia-pipemenu b/bl-multimedia-pipemenu
--- a/bl-multimedia-pipemenu
+++ b/bl-multimedia-pipemenu
@@ -2,19 +2,17 @@
 # ---------------------------------------------------------------------
 # An Openbox pipemenu for Multimedia applications.
 #
-# Adapted from the Openbox Graphics pipemenu written for CrunchBang Linux
-# <http://crunchbang.org/> by Philip Newborough (aka corenominal) <mail@philipnewborough.co.uk>
+# Originally written for CrunchBang Linux <http://crunchbang.org/>
+# by Philip Newborough (aka corenominal) <mail@philipnewborough.co.uk>
 #
 # Modified by damo for BunsenLabs Linux
 # ---------------------------------------------------------------------
 
 BL_COMMON_LIBDIR='/usr/lib/bunsen/bunsen-common'
+BL_INCLUDE='/usr/bin'
 
 # In order to add another APP, add the package name to this array:
-PLAYERS=( 'deadbeef' 'vlc' 'smplayer2' 'stuff' '' '')
-TOOLS=('mhwaveedit' 'openshot')
-UTILS=('volti' 'xfburn')
-
+APPS=( 'vlc' 'deadbeef' 'smplayer2' )
 
 # If the package needs additional configuration before installation
 # create a function called setupappName, it will be called automatically.
@@ -26,47 +24,16 @@ if ! . "$BL_COMMON_LIBDIR/bl-include.cfg" 2> /dev/null; then
 fi
 
 appExists() {
-	for curPlayer in "${PLAYERS[@]}"; do # if $packageName exists in players array
-		[[ $curPlayer = "$1" ]] &&
+	for curApp in "${APPS[@]}"; do # if $packageName exists in APPS array
+		[[ $curApp = "$1" ]] &&
 			return 0
 	done
 	say "Unable to install $1. There is no such application that I know of." 1 >&2
-	say "You can try one of these: ${PLAYERS[*]}" 2 >&2
-	sleep 5s
+	say "You can try one of these: ${APPS[*]}" 2 >&2
 	return 1
 }
 
-toolExists() {
-	for curTool in "${TOOLS[@]}"; do # if $packageName exists in tools array
-		[[ $curTool = "$1" ]] &&
-			return 0
-	done
-	say "Unable to install $1. There is no such application that I know of." 1 >&2
-	say "You can try one of these: ${TOOLS[*]}" 2 >&2
-	return 1
-}
 
-utilExists() {
-	for curUtil in "${UTILS[@]}"; do # if $packageName exists in utils array
-		[[ $curUtil = "$1" ]] &&
-			return 0
-	done
-	say "Unable to install $1. There is no such application that I know of." 1 >&2
-	say "You can try one of these: ${UTILS[*]}" 2 >&2
-	return 1
-}
-
-checkName() {	# set text to display in Menu
-	case "$1" in
-		"deadbeef"		) echo "DeaDBeef music player" ;;
-		"smplayer2"		) echo "Gnome Mplayer" ;;
-		"vlc"			) echo "VLC multimedia player";;
-		"mhwaveedit"	) echo "Sound editor" ;;
-		"openshot"		) echo "Openshot video editor" ;;
-		"volti"			) echo "Volti mixer" ;;
-		*				) echo "$1";;
-	esac
-}
 if [[ $1 && ! $1 = --install-* ]]; then
 	packageName=${1#--}
 	read -ra words <<< "${packageName//-/ }"
@@ -74,16 +41,7 @@ if [[ $1 && ! $1 = --install-* ]]; then
 
 elif [[ $1 = --install-* ]]; then
 	packageName=${1#--install-}
-	# check if package is from Tools array
-	if [[ $1 = --install-mhwaveedit ]] || [[ $1 = --install-openshot ]];then
-		toolExists "$packageName" || exit 1
-	# check if package is from Utilities array
-	elif [[ $1 = --install-volti ]] || [[ $1 = --install-xfburn ]];then
-		utilExists "$packageName" || exit 1
-	else
-		appExists "$packageName" || exit 1
-	fi
-
+	appExists "$packageName" || exit 1
 	appName=${packageName//-/ }
 	read -ra words <<< "$appName"
 	appName=${words[*]^}
@@ -98,41 +56,41 @@ elif [[ $1 = --install-* ]]; then
 
 else # pipemenu
 	menuStart
-	for curPlayer in "${PLAYERS[@]}"; do
-		read -ra words <<< "${curPlayer//-/ }"
-		curPlayerName=$(checkName "$curPlayer")
-		if type "$curPlayer" &> /dev/null; then
-			menuItem "$curPlayerName" "$curPlayer"
-		else
-			menuItem "Install $curPlayerName" "$0 --$curPlayer"
-		fi
-	done
-	menuSeparator 'Editors'
-
-	for curTool in "${TOOLS[@]}"; do
-		read -ra words <<< "${curTool//-/ }"
-		curToolName=$(checkName "$curTool")
-		if type "$curTool" &> /dev/null; then
-			menuItem "$curToolName" "$curTool"
-		else
-			menuItem "Install $curToolName" "$0 --$curTool"
-		fi
-	done
-	menuSeparator 'Utilities'
-	for curUtil in "${UTILS[@]}"; do
-		read -ra words <<< "${curUtil//-/ }"
-		curUtilName=$(checkName "$curUtil")
-		if type "$curUtil" &> /dev/null; then
-			if [[ "$curUtil" = "volti" ]] ; then
-				# volti mixer command is "volti-mixer"
-				menuItem "$curUtilName" "$curUtil-mixer"
+	for curApp in "${APPS[@]}"; do
+		read -ra words <<< "${curApp//-/ }"
+		curAppName=${words[*]^}
+		if type "$curApp" &> /dev/null; then
+			# change name of smplayer2
+			if [[ "$curApp" = "smplayer2" ]];then
+				menuItem "Gnome mplayer" "$curApp"
+				curAppName=${words[*]^}
 			else
-				menuItem "$curUtilName" "$curUtil"
+				menuItem "$curAppName" "$curApp"
 			fi
 		else
-			menuItem "Install $curUtilName" "$0 --$curUtil"
+			if [[ "$curAppName" == "Smplayer2" ]]; then
+				menuItem "Install Gnome mplayer" "$0 --$curApp"
+			else
+				menuItem "Install $curAppName" "$0 --$curApp"
+			fi
 		fi
 	done
+
+	menuSeparator 'Editors'
+	if ! type "$BL_INCLUDE/bl-media1-pipemenu" &> /dev/null; then
+		echo $"Error: Failed to locate submenu in $BL_INCLUDE" >&2
+		exit 1
+	else
+		echo $(/usr/bin/bl-media1-pipemenu)
+	fi
+
+	menuSeparator 'Utilities'
+	if ! type "$BL_INCLUDE/bl-media2-pipemenu" &> /dev/null; then
+		echo $"Error: Failed to locate submenu in $BL_INCLUDE" >&2
+		exit 1
+	else
+		echo $(/usr/bin/bl-media2-pipemenu)
+	fi
 	menuEnd
 fi
 exit 0
