rewrite testing if-clause; remove superfluous comments

diff --git a/bl-recent-files-pipemenu b/bl-recent-files-pipemenu
--- a/bl-recent-files-pipemenu
+++ b/bl-recent-files-pipemenu
@@ -171,16 +171,9 @@ done
 # probe for the user-provided file, or try to auto-detect a file
 
 if test -n "$BOOKMARKS_FILE" ; then
-  # check user-provided file for validity
-  if ! test -r "$BOOKMARKS_FILE" ; then
-    die "cannot read file: $BOOKMARKS_FILE"
-  fi
+  test -r "$BOOKMARKS_FILE" || die "cannot read file: $BOOKMARKS_FILE"
 else
-  # try to auto-detect a file
-  BOOKMARKS_FILE=$(detect_bookmarks_file "$COMMON_NAME")
-  if test $? -ne 0 ; then
-    die "failed to detect a recently-used file"
-  fi
+  BOOKMARKS_FILE=$(detect_bookmarks_file "$COMMON_NAME") || die "failed to detect a recently-used file"
 fi
 
 mk_application_file_column "$BOOKMARKS_FILE" "$FILE_COLUMN_FILENAME"
