Fix some bugs in bl-x-www-browser-pipemenu. Update changelog.

diff --git a/bl-x-www-browser-pipemenu b/bl-x-www-browser-pipemenu
--- a/bl-x-www-browser-pipemenu
+++ b/bl-x-www-browser-pipemenu
@@ -7,8 +7,8 @@
 
 BL_COMMON_LIBDIR='/usr/lib/bunsen/bunsen-common'
 
-# In order to add another browser, simply add it to this array:
-TOOLS=('chromium' 'iceweasel' 'google-chrome' 'opera')
+# In order to add another browser, add the package name to this array:
+TOOLS=('chromium' 'iceweasel' 'google-chrome-stable' 'opera' )
 # If the package needs additional configuration before installation simply create a function called setupBrowserName, it will be called automatically.
 
 KEY_URLS_GOOGLE=('https://dl-ssl.google.com/linux/linux_signing_key.pub' 'http://packages.crunchbang.org/waldorf-files/apt-keys/google-chrome.key')
@@ -24,29 +24,34 @@ browserExists() {
         [[ $curTool = "$1" ]] &&
             return 0
     done
-    say "Unable to install $1. There is no such browser that I know of." >&2
-    say "You can try one of these: ${TOOLS[@]}" >&2
+    say "Unable to install $1. There is no such browser that I know of." 1 >&2
+    say "You can try one of these: ${TOOLS[*]}" 2 >&2
     return 1
 }
 
 addAptKey() {
     clear
     say 'Adding APT key...'
-    keyFile=$(mktemp -u)
+    keyFile=$(mktemp)
     for curKey; do
-        wget -O "$keyFile" "$curKey" 2> /dev/null && break; # success. No need to try other keys
+        wget -O "$keyFile" "$curKey" 2> /dev/null && {
+            gotKey=true
+            say 'Key downloaded.'
+            break
+        } # success. No need to try other keys
         say "Failed to retrieve key from $curKey . Trying another source..."
     done
-    if [[ $? != 0 ]]; then
+    if ! $gotKey; then
         say 'Failed to retrieve APT key!' >&2
         return 1
     fi
+    say 'Adding key'
     sudo apt-key add "$keyFile"
     rm -f "$keyFile"
     return 0
 }
 
-setupGoogleChrome() {
+setupGoogleChromeStable() {
     addAptKey "${KEY_URLS_GOOGLE[@]}" || return 1
     say 'Creating APT sources file...' 1
     echo 'deb http://dl.google.com/linux/chrome/deb/ stable main' | sudo tee '/etc/apt/sources.list.d/google-chrome.list'
@@ -58,11 +63,11 @@ setupOpera() {
     echo 'deb http://deb.opera.com/opera/ stable non-free' | sudo tee '/etc/apt/sources.list.d/opera.list'
 }
 
-if [[ $1 && ! $1 =~ --install-* ]]; then
-    browserName=${1#--}
-    browserExists "$browserName" || exit 1
-    read -ra words <<< "${browserName//-/ }"
-    x-terminal-emulator --title "Install ${words[*]^}" -e "$0" "--install-$browserName"
+if [[ $1 && ! $1 = --install-* ]]; then
+    packageName=${1#--}
+#    browserExists "$packageName" || exit 1 # would fail silently
+    read -ra words <<< "${packageName//-/ }"
+    x-terminal-emulator --title "Install ${words[*]^}" -e "$0" "--install-$packageName"
 
 elif [[ $1 = --install-* ]]; then
     packageName=${1#--install-}
@@ -93,7 +98,7 @@ elif [[ $1 = --install-* ]]; then
         connectiontest 1 || continue
 
         setupFunctionName="setup${browserName//[^a-zA-Z]/}" # setupFunctionName should now be in format like 'setupChromium'
-        if [[ $(type -t "$setupFunctionName") == 'function' ]]; then
+        if [[ $(type -t "$setupFunctionName") = 'function' ]]; then
             "$setupFunctionName" || continue # run setup function if it exists
         fi
 
@@ -114,6 +119,7 @@ elif [[ $1 = --install-* ]]; then
         break
     done
 else # pipemenu
+    INSTALLED=false
     menuStart
     for curTool in "${TOOLS[@]}"; do
         read -ra words <<< "${curTool//-/ }"
@@ -121,7 +127,7 @@ else # pipemenu
         if type "$curTool" &> /dev/null; then
             INSTALLED=true
             menuItem "$curToolName" "$curTool"
-            [[ $curToolName =~ 'Chrom' ]] &&
+            [[ $curTool = chrom* ]] &&
                 menuItem "$curToolName (Private Mode)" "$curTool --incognito" # Incognito mode for chrome and chromium
         else
             menuItem "Install $curToolName" "$0 --$curTool"
